In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random

In [2]:

class ThreeLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.l1 = np.random.randint(2,8)
        self.l2 = np.random.randint(2,8)
        self.l3 = np.random.randint(2,8)

    def forwardKinematics(self, theta1, theta2, theta3):
        # Define the homogeneous transformation matrices for the 3-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], [np.sin(self.theta1), np.cos(self.theta1), 0], [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1], [np.sin(self.theta2), np.cos(self.theta2), 0], [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])        
        self.t3end = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l3], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])
        self.t0end = self.t01*self.t12*self.t23*self.t3end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        # Find the x, y coordinates for joints 2 and 3. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.endEffPos = j2,j3,endeff
        return j2,j3,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2)]).T 
        return J

In [3]:
def plotArm(jnt2pos, jnt3pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, endEffectPos,x2,y2,target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt2pos[0],x2[0]],[jnt2pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt2pos[0],x2[1]],[jnt2pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = ThreeLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, endEffectorPos = init_joint2pos, init_joint3pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len=np.random.randint(2,arm.l2+1)
    
    keypoints_data=pd.DataFrame(columns=range((4+2)*2),dtype=float)

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2])
        joint2pos, joint3pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motionv9/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((4+2,4+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[1][4]=1
    adj_mat[1][5]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motionv9/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motionv9/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
# create_simulation(7004,50)

In [6]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [7]:
for i in range(500,625):
    create_simulation(i,50)

16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -0.3168705 ]
 [  5.33333333   5.52885259]
 [ -5.33333333  10.37838115]
 [-10.66666667   3.96637128]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           2.41770149]
 [  5.          -7.5207281 ]
 [ -5.           7.86399074]
 [-10.           0.34321888]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  2.69778748]
 [ 4.66666667  8.11818776]
 [-4.66666667  7.57826559]
 [-9.33333333 -3.36727722]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   1.23564871]
 [  5.33333333  -4.72664612]
 [ -5.33333333   4.61598692]
 [-10.66666667  -3.59614023]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -4.40092556]
 [  5.66666667   3.70881217]
 [ -5.66666667   0.8198215 ]
 [-11.33333333   4.42548023]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667  0.52497964]
 [ 3.33333333  1.98819755]
 [-3.33333333  2.68575168]
 [-6.66666667  0.40361509]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          0.15599461]
 [ 4.          2.58513496]
 [-4.          7.13634495]
 [-8.         -2.12681803]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667  1.26424649]
 [ 3.33333333  5.49617144]
 [-3.33333333  0.82380958]
 [-6.66666667 -0.40230838]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -3.30598135]
 [ 4.33333333 -0.25781782]
 [-4.33333333  0.63605156]
 [-8.66666667 -2.2902952 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.          1.42926763]
 [ 4.          6.49739127]
 [-4.         -5.80309745]
 [-8.         -2.12184223]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.         -2.93027048]
 [ 3.         -6.00194375]
 [-3.          1.51572149]
 [-6.          0.09151691]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667 -4.26905486]
 [ 4.33333333  3.22144731]
 [-4.33333333  8.44060062]
 [-8.66666667 -0.62451361]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -0.84457623]
 [ 4.66666667 -5.55213677]
 [-4.66666667  6.07253007]
 [-9.33333333  4.60078139]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -3.15750632]
 [  5.          -2.44433494]
 [ -5.           7.11288384]
 [-10.          -4.63522696]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -3.43776157]
 [ 4.33333333 -6.52517104]
 [-4.33333333  0.92309708]
 [-8.66666667 -0.09088145]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   3.03413482]
 [  5.66666667 -10.38482916]
 [ -5.66666667 -10.5350582 ]
 [-11.33333333   4.6935653 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -0.33133192]
 [  5.          -1.92101501]
 [ -5.           0.47170651]
 [-10.          -4.51073268]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          3.63185118]
 [ 4.         -2.03407106]
 [-4.         -2.699284  ]
 [-8.         -2.70692155]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.53553391  3.53553391]
 [ 7.33333333 -0.79165872]
 [ 3.66666667 -0.36653832]
 [-3.66666667  2.81428742]
 [-7.33333333 -0.52939934]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.53553391  3.53553391]
 [ 6.66666667  3.04434579]
 [ 3.33333333 -0.33173749]
 [-3.33333333  0.31542609]
 [-6.66666667  0.07238109]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333 -2.49815313]
 [ 4.66666667 -8.08975271]
 [-4.66666667  7.1120129 ]
 [-9.33333333 -1.58900255]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667  1.24521802]
 [ 4.33333333 -4.81619965]
 [-4.33333333  1.67727227]
 [-8.66666667  4.39414524]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -2.21137806]
 [  5.33333333  10.42190207]
 [ -5.33333333  -8.08265055]
 [-10.66666667   0.50801367]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333 -0.82267322]
 [ 3.66666667  0.35048635]
 [-3.66666667 -0.27793855]
 [-7.33333333 -2.20856225]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           2.63056523]
 [  5.          -8.60871528]
 [ -5.           2.65683634]
 [-10.          -3.42231537]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.94974747  4.94974747]
 [ 8.66666667 -2.50202664]
 [ 4.33333333  1.53505786]
 [-4.33333333  0.58880984]
 [-8.66666667  3.01332817]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.          -0.39029685]
 [  5.          -3.01560825]
 [ -5.          -0.40740139]
 [-10.           0.24932956]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   3.94765792]
 [  5.33333333   3.83535513]
 [ -5.33333333  10.07814677]
 [-10.66666667   0.40577724]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.12132034  2.12132034]
 [ 8.         -2.80991327]
 [ 4.          3.39610984]
 [-4.         -3.41053689]
 [-8.         -2.45672435]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.           4.39543747]
 [  5.           3.03420771]
 [ -5.          -2.68123649]
 [-10.           2.1863482 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -0.15534594]
 [  6.           5.21208885]
 [ -6.          -5.25983678]
 [-12.           1.03309888]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -2.21121268]
 [ 4.33333333  3.56852367]
 [-4.33333333 -8.47624725]
 [-8.66666667  1.64172128]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333 -3.17813905]
 [ 3.66666667  1.1054444 ]
 [-3.66666667  0.0544333 ]
 [-7.33333333  0.13522768]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.         -4.02078225]
 [ 4.         -4.97970911]
 [-4.         -6.56297446]
 [-8.          1.62370231]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.12132034   2.12132034]
 [ 11.33333333   1.96998481]
 [  5.66666667  -7.94877697]
 [ -5.66666667   5.57572144]
 [-11.33333333   5.51560503]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -2.71157781]
 [  5.33333333   7.49256753]
 [ -5.33333333  -4.10997223]
 [-10.66666667   4.96782137]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -2.42786529]
 [  5.          -5.8937276 ]
 [ -5.           3.09619336]
 [-10.           4.74030833]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -5.52136259]
 [  6.          -6.0260444 ]
 [ -6.          -1.51207501]
 [-12.          -0.49826695]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667 -4.28665266]
 [ 4.33333333  5.99001526]
 [-4.33333333 -3.36822579]
 [-8.66666667  4.17444912]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   3.36046065]
 [  6.33333333   4.06832227]
 [ -6.33333333  -0.83892525]
 [-12.66666667   3.97934772]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          2.8392126 ]
 [ 4.          4.19129721]
 [-4.          3.41249678]
 [-8.          3.65233122]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


7
The interpolation points are stored in the variable "EF_target_pos": 
[[ 6.41421356  1.41421356]
 [ 4.66666667  1.45988054]
 [ 2.33333333 -3.11697293]
 [-2.33333333  2.10062524]
 [-4.66666667  0.43559096]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.41421356  1.41421356]
 [ 6.         -2.94355933]
 [ 3.          4.40877044]
 [-3.         -1.2150677 ]
 [-6.         -0.16115145]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.82842712  2.82842712]
 [ 6.          1.24241409]
 [ 3.         -1.28723432]
 [-3.         -5.81709326]
 [-6.         -2.25515167]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -4.0573197 ]
 [ 4.33333333  1.16873705]
 [-4.33333333  3.67163811]
 [-8.66666667 -2.44176523]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667 -3.19514752]
 [ 4.33333333  2.44310049]
 [-4.33333333  5.95558965]
 [-8.66666667  3.62123553]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.82842712  2.82842712]
 [ 6.66666667 -0.44309696]
 [ 3.33333333  2.92636457]
 [-3.33333333  3.97657492]
 [-6.66666667  0.49654079]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667  3.92571577]
 [ 4.33333333  3.95431917]
 [-4.33333333 -2.50795128]
 [-8.66666667 -3.15797142]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           4.82389181]
 [  5.          -9.50429286]
 [ -5.           5.48332103]
 [-10.           4.73182368]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667 -1.41604654]
 [ 4.33333333 -2.24070811]
 [-4.33333333  5.28042334]
 [-8.66666667  3.16856393]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -0.14091172]
 [  5.33333333   5.17280377]
 [ -5.33333333   1.42699019]
 [-10.66666667  -0.60699007]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -1.87128318]
 [ 4.33333333  1.58344412]
 [-4.33333333  4.51589345]
 [-8.66666667  3.84231123]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.12132034  2.12132034]
 [ 7.33333333  2.33821602]
 [ 3.66666667 -4.21386389]
 [-3.66666667 -4.69486164]
 [-7.33333333  1.74526832]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          1.3246413 ]
 [ 4.         -7.09751426]
 [-4.         -8.03576506]
 [-8.          0.78599888]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667  4.11830781]
 [ 4.33333333 -7.83131632]
 [-4.33333333 -6.34244061]
 [-8.66666667  3.91913083]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.53553391  3.53553391]
 [ 6.66666667 -2.14827496]
 [ 3.33333333 -4.0203246 ]
 [-3.33333333 -6.62836156]
 [-6.66666667 -0.49024978]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.12132034  2.12132034]
 [ 5.33333333  2.30922068]
 [ 2.66666667  1.97576761]
 [-2.66666667  3.07789057]
 [-5.33333333  0.10800872]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -4.07790672]
 [ 4.33333333  0.96633043]
 [-4.33333333  2.70742374]
 [-8.66666667  3.3377312 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.82842712  2.82842712]
 [ 6.66666667 -0.60723448]
 [ 3.33333333  5.33393642]
 [-3.33333333  5.29640439]
 [-6.66666667 -1.4296457 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.12132034  2.12132034]
 [ 5.33333333 -1.12758746]
 [ 2.66666667 -2.91923857]
 [-2.66666667  2.3801819 ]
 [-5.33333333 -0.683992  ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.12132034   2.12132034]
 [ 11.33333333   4.67090358]
 [  5.66666667  -3.66037307]
 [ -5.66666667   7.80479716]
 [-11.33333333   3.07949799]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -2.8222609 ]
 [ 4.66666667 -8.35683299]
 [-4.66666667 -5.47653683]
 [-9.33333333 -2.22061323]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


7
The interpolation points are stored in the variable "EF_target_pos": 
[[ 6.41421356  1.41421356]
 [ 4.66666667  2.17861969]
 [ 2.33333333 -1.71112444]
 [-2.33333333 -0.7905899 ]
 [-4.66666667 -0.99228672]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           2.03618989]
 [  6.          -1.13919816]
 [ -6.          11.81073749]
 [-12.           5.46832924]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           0.86256127]
 [  5.          -5.86241009]
 [ -5.          -2.15396795]
 [-10.          -2.09612616]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  0.95910004]
 [ 4.66666667  6.28909153]
 [-4.66666667  2.30102735]
 [-9.33333333 -1.95394837]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -0.23098265]
 [ 4.66666667 -2.13920256]
 [-4.66666667 -2.34243631]
 [-9.33333333 -1.91505143]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           3.52275209]
 [  7.          -6.78320531]
 [ -7.          13.37695175]
 [-14.           0.04708466]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667  3.25752889]
 [ 4.33333333  7.74418107]
 [-4.33333333  4.20423778]
 [-8.66666667  1.46520092]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.55355339e+01  3.53553391e+00]
 [ 1.13333333e+01  1.14234671e-02]
 [ 5.66666667e+00 -8.95502714e+00]
 [-5.66666667e+00 -1.06728832e+01]
 [-1.13333333e+01 -2.11923469e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -3.50923775]
 [  5.66666667  -7.79946052]
 [ -5.66666667  10.56282887]
 [-11.33333333  -4.95961239]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -2.89462274]
 [  5.66666667   3.6912514 ]
 [ -5.66666667  -0.79176249]
 [-11.33333333   4.13831444]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.94974747  4.94974747]
 [ 8.66666667 -1.73608965]
 [ 4.33333333  4.53652714]
 [-4.33333333 -6.3540539 ]
 [-8.66666667  0.78739058]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   0.89912932]
 [  5.66666667   3.30391032]
 [ -5.66666667  -8.8555033 ]
 [-11.33333333   5.07547007]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          3.68329424]
 [ 4.         -3.09876037]
 [-4.          5.7482019 ]
 [-8.          3.91497693]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           0.03492471]
 [  6.          -4.02960734]
 [ -6.          -0.51866178]
 [-12.          -4.18357424]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          2.92122471]
 [ 4.         -2.77901539]
 [-4.          7.63576752]
 [-8.          3.32833231]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.         -3.05316343]
 [ 4.         -0.04678313]
 [-4.          4.15269977]
 [-8.          0.68785029]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   4.39942355]
 [  6.33333333  -6.69700276]
 [ -6.33333333   5.02581547]
 [-12.66666667   0.95351047]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   3.7124579 ]
 [  5.66666667   5.41343386]
 [ -5.66666667  -2.83463501]
 [-11.33333333  -2.77588031]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.          0.20197895]
 [ 4.         -7.72922656]
 [-4.          4.40657656]
 [-8.         -3.75927585]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  3.20444507]
 [ 4.33333333  2.25232109]
 [-4.33333333  7.14247218]
 [-8.66666667  0.02313351]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667  1.10199847]
 [ 4.33333333 -6.38333573]
 [-4.33333333 -4.75940374]
 [-8.66666667  0.45037464]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667 -3.16928227]
 [ 4.33333333  3.86706829]
 [-4.33333333 -8.2808287 ]
 [-8.66666667 -2.95827169]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  2.62733804]
 [ 4.66666667  0.57296438]
 [-4.66666667  5.71874801]
 [-9.33333333  0.6084628 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  2.48565776]
 [ 4.66666667  0.31445249]
 [-4.66666667  7.04215777]
 [-9.33333333 -4.01841817]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -0.37119605]
 [ 4.33333333  4.47154145]
 [-4.33333333  0.1119333 ]
 [-8.66666667  3.38955067]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.53553391  3.53553391]
 [ 7.33333333  0.5578065 ]
 [ 3.66666667 -2.77985416]
 [-3.66666667 -1.59557479]
 [-7.33333333  0.72433917]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  3.00076084]
 [ 4.66666667 -8.09290751]
 [-4.66666667 -7.55082402]
 [-9.33333333  2.96941293]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  3.64882691]
 [ 4.33333333  4.01822245]
 [-4.33333333 -0.34313401]
 [-8.66666667  0.12174149]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  2.70547915]
 [ 4.33333333  0.25594291]
 [-4.33333333  1.06042279]
 [-8.66666667 -4.17025079]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.12132034   2.12132034]
 [ 10.66666667   1.75697498]
 [  5.33333333   2.63629154]
 [ -5.33333333   5.81111975]
 [-10.66666667   1.71695119]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667  3.93050293]
 [ 4.33333333  4.03330656]
 [-4.33333333 -1.04755247]
 [-8.66666667  4.29583868]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.53553391  3.53553391]
 [ 7.33333333 -0.26232444]
 [ 3.66666667  5.06323122]
 [-3.66666667 -1.50777394]
 [-7.33333333 -1.5257432 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   3.45001355]
 [  5.66666667   3.61463455]
 [ -5.66666667  -1.41013512]
 [-11.33333333   3.70653466]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -4.22371988]
 [  6.33333333   3.05524312]
 [ -6.33333333  -5.40362387]
 [-12.66666667   6.47288633]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -3.45467187]
 [  5.33333333  -5.54325942]
 [ -5.33333333   9.18304386]
 [-10.66666667  -4.93723425]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.12132034  2.12132034]
 [ 6.66666667 -2.75271104]
 [ 3.33333333  1.7087214 ]
 [-3.33333333  1.93567259]
 [-6.66666667  0.01257428]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.41421356  1.41421356]
 [ 7.33333333  0.84899391]
 [ 3.66666667  3.48722154]
 [-3.66666667 -0.60154088]
 [-7.33333333 -0.71160385]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 6.82842712  2.82842712]
 [ 5.33333333  2.32752272]
 [ 2.66666667  1.72675603]
 [-2.66666667  4.35963835]
 [-5.33333333  0.50693684]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           1.55669282]
 [  6.          -2.05164881]
 [ -6.           1.86614059]
 [-12.          -5.26249507]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -2.40369271]
 [ 4.66666667 -1.46258623]
 [-4.66666667 -0.62719352]
 [-9.33333333  4.68771847]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.12132034  2.12132034]
 [ 7.33333333  2.85476594]
 [ 3.66666667 -3.28850286]
 [-3.66666667  6.34699256]
 [-7.33333333 -0.24547365]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   2.19490489]
 [  5.66666667  -2.08734635]
 [ -5.66666667  -3.25427098]
 [-11.33333333  -0.8960014 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   0.81095166]
 [  5.33333333   9.10504241]
 [ -5.33333333   9.55839959]
 [-10.66666667  -4.91607003]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   4.58677073]
 [  5.33333333  -2.4726206 ]
 [ -5.33333333  -8.94811651]
 [-10.66666667  -2.9825258 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -1.28935803]
 [  5.33333333  -2.53879638]
 [ -5.33333333   8.31299921]
 [-10.66666667  -5.29134933]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.          2.47717355]
 [ 3.         -3.39944965]
 [-3.          1.20023066]
 [-6.          0.02961898]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667  0.78935391]
 [ 3.33333333 -3.59702924]
 [-3.33333333 -0.31779753]
 [-6.66666667  2.68334673]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.82842712  2.82842712]
 [ 6.66666667 -1.74789628]
 [ 3.33333333 -5.92738924]
 [-3.33333333 -1.5272573 ]
 [-6.66666667  0.84402992]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667 -2.97121876]
 [ 3.33333333  4.23251687]
 [-3.33333333 -5.52880658]
 [-6.66666667  0.46930103]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.         -1.08830769]
 [ 4.          3.22807545]
 [-4.         -2.57382228]
 [-8.          0.83903635]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.41421356  1.41421356]
 [ 7.33333333 -3.53367236]
 [ 3.66666667 -3.99326451]
 [-3.66666667  0.54947671]
 [-7.33333333  0.48862255]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.41421356  1.41421356]
 [ 7.33333333 -1.39293098]
 [ 3.66666667 -0.97383483]
 [-3.66666667  6.66615275]
 [-7.33333333 -2.17821538]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -5.69665537]
 [  6.          11.86451121]
 [ -6.           6.7322313 ]
 [-12.           5.09536711]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.82842712  2.82842712]
 [ 6.          2.06819369]
 [ 3.          2.91211005]
 [-3.          3.17155389]
 [-6.         -1.93529577]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   5.36053172]
 [  5.66666667   0.12082949]
 [ -5.66666667   6.13658752]
 [-11.33333333  -4.39949648]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.         -2.71463272]
 [ 4.          3.4239592 ]
 [-4.          7.25796359]
 [-8.          1.90281375]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  3.44793828]
 [ 4.33333333 -5.32814544]
 [-4.33333333  2.79143079]
 [-8.66666667  4.09138941]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.41421356  1.41421356]
 [ 6.          2.76815856]
 [ 3.         -5.79271069]
 [-3.         -2.08231346]
 [-6.         -0.60239274]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667  2.61655198]
 [ 4.33333333  0.26323706]
 [-4.33333333 -7.97244464]
 [-8.66666667 -0.84870627]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.53553391  3.53553391]
 [ 7.33333333 -2.03321857]
 [ 3.66666667  3.70467203]
 [-3.66666667 -7.04564074]
 [-7.33333333  3.49365768]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[13.41421356  1.41421356]
 [ 9.33333333 -0.79960907]
 [ 4.66666667 -2.9159712 ]
 [-4.66666667 -6.41593794]
 [-9.33333333  4.74877319]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.           1.18992085]
 [  5.          -3.93980241]
 [ -5.          -9.35487302]
 [-10.          -3.06115704]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.53553391  3.53553391]
 [ 6.66666667 -2.79160871]
 [ 3.33333333 -1.03846915]
 [-3.33333333 -0.99022227]
 [-6.66666667  0.53833838]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
