In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random
import copy

In [2]:

class ThreeLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.orig_l1 = np.random.randint(4,9)
        self.orig_l2 = np.random.randint(4,9)
        self.orig_l3 = np.random.randint(4,9)
        self.l1=copy.copy(self.orig_l1)
        self.l2=copy.copy(self.orig_l2)
        self.l3=copy.copy(self.orig_l3)
        max_len_shift=int(np.min([self.l1,self.l2,self.l3])*(2/3))
        self.arr1=np.linspace(-max_len_shift,max_len_shift,np.random.randint(10,50))
        self.arr1=np.append(self.arr1,np.flip(self.arr1))
        self.permute=np.random.permutation([0.5,0.5,-1])


    def forwardKinematics(self, theta1, theta2, theta3):
        # Define the homogeneous transformation matrices for the 3-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], [np.sin(self.theta1), np.cos(self.theta1), 0], [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1], [np.sin(self.theta2), np.cos(self.theta2), 0], [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])        
        self.t3end = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l3], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])
        self.t0end = self.t01*self.t12*self.t23*self.t3end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        # Find the x, y coordinates for joints 2 and 3. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.endEffPos = j2,j3,endeff
        return j2,j3,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2)]).T 
        return J
    
    def random_link_len_change(self,i):
        self.l1=self.orig_l1+self.permute[0]*self.arr1[i%len(self.arr1)]
        self.l2=self.orig_l2+self.permute[1]*self.arr1[i%len(self.arr1)]
        self.l3=self.orig_l3+self.permute[2]*self.arr1[i%len(self.arr1)]

In [3]:
def plotArm(jnt2pos, jnt3pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, endEffectPos,x2,y2,target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt2pos[0],x2[0]],[jnt2pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt2pos[0],x2[1]],[jnt2pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = ThreeLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, endEffectorPos = init_joint2pos, init_joint3pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len_orig=np.random.randint(2,arm.l2+1)
    
    keypoints_data=pd.DataFrame(columns=range((4+2)*2),dtype=float)
    
    arr2=np.linspace(-int(wrist_len_orig/2),int(wrist_len_orig/2),np.random.randint(10,50))
    
    arr2=np.append(arr2,np.flip(arr2))

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        arm.random_link_len_change(i)
        wrist_len=wrist_len_orig+arr2[i%len(arr2)]

        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2])
        joint2pos, joint3pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motion_dynamic_len/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((4+2,4+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[1][4]=1
    adj_mat[1][5]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motion_dynamic_len/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motion_dynamic_len/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [6]:
# create_simulation(1024,50)

In [7]:
for i in range(500,625):
    create_simulation(i,50)

19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -6.20489209]
 [  6.33333333   1.8446877 ]
 [ -6.33333333   4.13025371]
 [-12.66666667  -0.5052279 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   1.42022902]
 [  6.33333333  -0.59938637]
 [ -6.33333333   2.91497113]
 [-12.66666667  -4.54766546]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.82842712   2.82842712]
 [ 11.33333333  -4.13754977]
 [  5.66666667  -7.40680173]
 [ -5.66666667  10.85472718]
 [-11.33333333  -5.2231683 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -1.41551889]
 [  6.66666667  -9.77287976]
 [ -6.66666667 -11.75629837]
 [-13.33333333  -6.60995945]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -2.35044866]
 [  5.          -7.36667801]
 [ -5.           4.1065247 ]
 [-10.           3.94631481]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -0.26264109]
 [  6.           3.42934813]
 [ -6.          -2.69895193]
 [-12.          -2.85183318]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667 -3.70124855]
 [ 4.33333333 -1.70121139]
 [-4.33333333  1.46609264]
 [-8.66666667 -2.80082895]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -0.64738835]
 [  5.66666667   9.27758067]
 [ -5.66666667   8.84370557]
 [-11.33333333  -3.98007899]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.82842712   2.82842712]
 [ 11.33333333  -1.42843592]
 [  5.66666667  -6.19504275]
 [ -5.66666667 -10.42896049]
 [-11.33333333   4.84737452]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   1.34858984]
 [  6.33333333   1.69625756]
 [ -6.33333333   8.02791383]
 [-12.66666667  -0.58712578]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.          -5.3262545 ]
 [  7.          -5.42154319]
 [ -7.         -13.53483219]
 [-14.           2.79620431]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -1.01477828]
 [ 4.66666667  3.61399738]
 [-4.66666667 -6.38293565]
 [-9.33333333 -1.13427666]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.         -1.46984668]
 [ 4.         -0.7759785 ]
 [-4.          5.14729492]
 [-8.          2.28347354]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  3.29407893]
 [ 4.33333333  4.080517  ]
 [-4.33333333  3.89331109]
 [-8.66666667 -1.97235698]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667  3.32870459]
 [ 4.33333333  0.51223792]
 [-4.33333333 -0.12597435]
 [-8.66666667  1.02315336]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -2.49187532]
 [  6.66666667  -7.64512494]
 [ -6.66666667   3.13011369]
 [-13.33333333  -4.98636922]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.82842712   2.82842712]
 [ 11.33333333  -5.48672729]
 [  5.66666667  11.36034576]
 [ -5.66666667  -3.09573249]
 [-11.33333333   4.88494928]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -4.18290446]
 [  5.33333333   7.53044611]
 [ -5.33333333  -1.76090938]
 [-10.66666667   2.03311778]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333  -0.78389264]
 [  6.66666667   1.10476801]
 [ -6.66666667  10.25313321]
 [-13.33333333   0.79463388]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.82842712   2.82842712]
 [ 13.33333333   4.68425421]
 [  6.66666667   6.83531376]
 [ -6.66666667  -5.95266163]
 [-13.33333333   5.75748475]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -3.01583582]
 [ 4.66666667 -8.44911854]
 [-4.66666667  7.30110002]
 [-9.33333333 -4.3115251 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   0.82730074]
 [  5.66666667  -5.98156912]
 [ -5.66666667  -7.62402382]
 [-11.33333333   3.94907419]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333  -2.53283215]
 [  5.66666667  -3.70931503]
 [ -5.66666667   3.74540527]
 [-11.33333333  -5.42342878]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -2.97157149]
 [  7.33333333 -14.24798861]
 [ -7.33333333  12.62213785]
 [-14.66666667  -1.3528184 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   0.877132  ]
 [  5.66666667  -1.54067163]
 [ -5.66666667   0.27623855]
 [-11.33333333   3.90078438]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -0.60815798]
 [  5.66666667   0.1951665 ]
 [ -5.66666667 -10.4911894 ]
 [-11.33333333  -3.77723193]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           1.56076762]
 [  6.          -4.32927907]
 [ -6.          -9.40473219]
 [-12.          -2.2640625 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.          -3.57689452]
 [  6.           0.27684028]
 [ -6.         -11.03822667]
 [-12.          -3.28231576]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  1.82845575]
 [ 4.66666667 -6.9455161 ]
 [-4.66666667 -6.15174479]
 [-9.33333333  2.03468352]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   3.75135753]
 [  5.33333333   7.92216231]
 [ -5.33333333  -3.2624768 ]
 [-10.66666667   3.69397484]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           3.55816496]
 [  6.          -9.77565521]
 [ -6.           7.62447205]
 [-12.           2.18336767]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   2.27217285]
 [  5.66666667   8.39636184]
 [ -5.66666667   8.44996729]
 [-11.33333333  -4.01006001]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.51330679]
 [  6.33333333 -10.93759795]
 [ -6.33333333  -7.6733895 ]
 [-12.66666667   3.66595515]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.65685425   5.65685425]
 [ 15.33333333   5.90602738]
 [  7.66666667  -5.36874813]
 [ -7.66666667   8.98720048]
 [-15.33333333  -3.17509318]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.          -2.60274924]
 [  7.          -0.83746137]
 [ -7.           9.14202309]
 [-14.          -2.30166683]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   5.54741726]
 [  6.33333333  12.39794038]
 [ -6.33333333  -3.17198336]
 [-12.66666667  -2.12152421]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   3.14691641]
 [  5.33333333  -7.8809123 ]
 [ -5.33333333   0.07856548]
 [-10.66666667   1.61206123]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -5.42921297]
 [  6.33333333  -2.60653681]
 [ -6.33333333  -8.80413248]
 [-12.66666667   1.42044669]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.          -0.73277714]
 [  6.           4.19295958]
 [ -6.           6.46729476]
 [-12.          -5.15296011]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   5.62048515]
 [  5.66666667  -9.41351998]
 [ -5.66666667  -6.54999422]
 [-11.33333333   3.91816652]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -2.15712933]
 [  6.          -5.83380459]
 [ -6.          -7.28839453]
 [-12.           1.63795492]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -0.2602154 ]
 [  5.66666667  -7.58577704]
 [ -5.66666667  -2.27562305]
 [-11.33333333  -1.78617366]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -2.24625651]
 [  5.33333333   1.61061695]
 [ -5.33333333  -0.97577031]
 [-10.66666667   2.25593672]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           5.31504644]
 [  6.          -6.24806348]
 [ -6.          -9.06956058]
 [-12.           3.28923749]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.34899364]
 [  6.33333333  -7.51802434]
 [ -6.33333333   0.68788102]
 [-12.66666667   0.46204462]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -4.30111063]
 [  6.           8.97470909]
 [ -6.           8.69079474]
 [-12.          -3.95320088]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.82842712   2.82842712]
 [ 11.33333333  -2.66591293]
 [  5.66666667   9.83127189]
 [ -5.66666667   6.17472118]
 [-11.33333333  -4.16607214]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   5.42380863]
 [  5.66666667  -4.3530087 ]
 [ -5.66666667   5.31584437]
 [-11.33333333   0.58436487]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -2.94471929]
 [  6.33333333   6.71825634]
 [ -6.33333333  -9.4390542 ]
 [-12.66666667  -5.51018719]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   1.33217157]
 [  6.66666667  -3.12249572]
 [ -6.66666667   5.24587447]
 [-13.33333333   3.93504321]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667   3.70018644]
 [  5.33333333   5.2990701 ]
 [ -5.33333333  -1.4370656 ]
 [-10.66666667  -5.28916013]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333 -0.16506188]
 [ 4.66666667  7.36682565]
 [-4.66666667  9.30739798]
 [-9.33333333 -1.87459381]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -2.79437964]
 [  6.           1.32630474]
 [ -6.          -1.94347906]
 [-12.          -2.42752677]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -3.87372168]
 [  5.33333333   4.84395696]
 [ -5.33333333  -9.72988694]
 [-10.66666667  -5.02122618]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.82842712   2.82842712]
 [ 13.33333333   5.06729493]
 [  6.66666667  -1.37482637]
 [ -6.66666667  -0.10555732]
 [-13.33333333   1.32672632]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   0.28845786]
 [  6.66666667   6.47328563]
 [ -6.66666667  -2.96397751]
 [-13.33333333  -2.09708554]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.          -6.78898396]
 [  7.          -7.81596023]
 [ -7.           1.67284977]
 [-14.           2.72774443]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -1.97599108]
 [  6.          -9.18379575]
 [ -6.          -9.72883198]
 [-12.          -4.84034874]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   2.23210578]
 [  5.66666667   8.34737785]
 [ -5.66666667   6.36017619]
 [-11.33333333  -3.69633931]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -4.00325297]
 [  5.66666667  10.26738239]
 [ -5.66666667   3.03316502]
 [-11.33333333   1.24986192]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.24264069   4.24264069]
 [ 14.           3.97486966]
 [  7.          11.06076037]
 [ -7.           9.64408272]
 [-14.           1.96005175]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   5.82714447]
 [  6.66666667  -8.44481763]
 [ -6.66666667   9.3767958 ]
 [-13.33333333  -3.19205261]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -5.27729298]
 [  5.66666667   6.97902771]
 [ -5.66666667   3.57429129]
 [-11.33333333   1.21245476]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           1.91475571]
 [  6.          -8.14515589]
 [ -6.           0.59847183]
 [-12.           3.9773417 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -3.09985256]
 [  7.          -3.1472206 ]
 [ -7.          -9.61551953]
 [-14.           2.28293544]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   5.48172645]
 [  5.66666667  -5.0341909 ]
 [ -5.66666667   0.09988668]
 [-11.33333333   4.69634655]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -3.14079224]
 [  5.33333333  -3.61620378]
 [ -5.33333333  -4.45342034]
 [-10.66666667   1.98598781]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   2.21528187]
 [  5.33333333   4.22377883]
 [ -5.33333333 -10.20662887]
 [-10.66666667  -0.52631577]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -6.48054856]
 [  6.33333333   8.82892822]
 [ -6.33333333   8.75654988]
 [-12.66666667  -4.64777107]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   5.5940738 ]
 [  6.33333333  -3.56932017]
 [ -6.33333333  -9.31826934]
 [-12.66666667  -3.39667276]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -5.33372367]
 [  6.66666667   1.66775083]
 [ -6.66666667   0.65910181]
 [-13.33333333  -4.78331259]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.82842712   2.82842712]
 [ 12.66666667   6.23585133]
 [  6.33333333  -9.95774914]
 [ -6.33333333  -0.76786025]
 [-12.66666667   4.07477486]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333   4.23340241]
 [  6.66666667   7.05235124]
 [ -6.66666667   1.83534605]
 [-13.33333333  -6.52625537]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   5.74357061]
 [  5.66666667 -10.28068098]
 [ -5.66666667   5.22426267]
 [-11.33333333  -0.60530342]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -1.7538259 ]
 [  5.33333333   3.31054758]
 [ -5.33333333   3.67365856]
 [-10.66666667   1.34089145]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.          -1.56947069]
 [  7.          -9.24761045]
 [ -7.           6.76847522]
 [-14.          -3.44956948]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667  4.16488706]
 [ 4.33333333  3.6519225 ]
 [-4.33333333  4.64332765]
 [-8.66666667 -3.9081422 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.42776156]
 [  6.33333333   6.43563729]
 [ -6.33333333   1.94746233]
 [-12.66666667   3.80576341]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           2.19709353]
 [  5.          -6.11369894]
 [ -5.          -3.03937839]
 [-10.          -4.19831158]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           1.66377462]
 [  6.           1.43264024]
 [ -6.          -2.27959378]
 [-12.          -1.71380856]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   3.57305418]
 [  6.66666667  10.61676613]
 [ -6.66666667   4.92288063]
 [-13.33333333  -4.12891193]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   1.54766158]
 [  6.33333333  12.72886324]
 [ -6.33333333  -0.74053258]
 [-12.66666667  -0.3158836 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -3.12567998]
 [  5.33333333   5.39435449]
 [ -5.33333333   9.91546521]
 [-10.66666667  -0.14877549]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   2.01474288]
 [  5.66666667 -10.12476924]
 [ -5.66666667  -0.63663391]
 [-11.33333333   1.12746766]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           1.59427178]
 [  6.          -7.54583344]
 [ -6.           1.20318158]
 [-12.           0.2897082 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333   1.16689789]
 [  6.66666667   3.9923437 ]
 [ -6.66666667   1.8443881 ]
 [-13.33333333   6.22127204]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.           1.26265392]
 [  7.          -6.73078491]
 [ -7.          -1.34755833]
 [-14.           2.36119501]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           1.26369921]
 [  7.           9.96443257]
 [ -7.          11.39391225]
 [-14.          -6.63213791]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.          -5.132062  ]
 [  5.           6.21787778]
 [ -5.           5.04681474]
 [-10.          -5.07420323]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.          -2.3186115 ]
 [  5.          -0.81384305]
 [ -5.          -5.94727331]
 [-10.           3.3745935 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   2.61483157]
 [  6.33333333  -0.72543821]
 [ -6.33333333   6.33349136]
 [-12.66666667  -0.38089855]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -6.85823563]
 [  7.           4.01251288]
 [ -7.          -8.21110552]
 [-14.           6.63579756]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           4.48932022]
 [  6.          -3.27030271]
 [ -6.           7.11291847]
 [-12.           3.66418301]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.           2.99352664]
 [  7.          -2.17303154]
 [ -7.           3.31127038]
 [-14.           1.62142949]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   0.04607342]
 [  6.33333333   1.28626589]
 [ -6.33333333   5.25267218]
 [-12.66666667   2.55301542]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -1.19579362]
 [  6.33333333   2.45476733]
 [ -6.33333333  -1.3824801 ]
 [-12.66666667   5.06489737]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.82842712   2.82842712]
 [ 12.66666667  -2.30598404]
 [  6.33333333 -10.39148122]
 [ -6.33333333 -12.16411371]
 [-12.66666667   2.73940668]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -1.99206804]
 [  6.66666667  10.67755012]
 [ -6.66666667   1.6806361 ]
 [-13.33333333   0.87450284]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -4.45253402]
 [  6.          -3.41082287]
 [ -6.         -10.43768796]
 [-12.          -6.02973932]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -1.13225028]
 [  5.33333333  -7.37218849]
 [ -5.33333333   8.41132963]
 [-10.66666667  -2.58443301]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -2.2852804 ]
 [  5.33333333   3.82842817]
 [ -5.33333333  -7.98927684]
 [-10.66666667  -0.69933849]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   4.27108423]
 [  5.66666667   6.31046511]
 [ -5.66666667  -0.47458567]
 [-11.33333333   1.76600116]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.           1.28028455]
 [  7.          13.87329608]
 [ -7.         -10.04498673]
 [-14.           2.10386551]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           6.828621  ]
 [  7.           9.91353299]
 [ -7.          -8.93067907]
 [-14.          -4.72101241]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -2.2367958 ]
 [  5.33333333  10.5465303 ]
 [ -5.33333333   1.3284234 ]
 [-10.66666667  -5.00149714]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           2.32359879]
 [  5.          -2.03963252]
 [ -5.           2.72555201]
 [-10.           3.70404949]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   3.26294202]
 [  6.33333333  -1.948648  ]
 [ -6.33333333  -3.72991245]
 [-12.66666667   5.40784128]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           5.18772553]
 [  6.           6.77287019]
 [ -6.           7.43219952]
 [-12.          -5.5089976 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -4.03469668]
 [  5.66666667  -5.57005111]
 [ -5.66666667  -3.51799743]
 [-11.33333333  -0.49082981]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.           1.0858588 ]
 [  5.          -4.47397847]
 [ -5.           4.34303769]
 [-10.           1.73857627]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333   2.15970943]
 [  6.66666667  13.37003426]
 [ -6.66666667   9.75139568]
 [-13.33333333   1.34668721]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.          -6.46849275]
 [  7.           7.70631764]
 [ -7.           3.89095617]
 [-14.           0.56610188]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  0.6447934 ]
 [ 4.66666667 -4.43891771]
 [-4.66666667  8.01216732]
 [-9.33333333  0.59957385]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           6.0897781 ]
 [  7.           8.3783972 ]
 [ -7.          -2.7074795 ]
 [-14.           5.11899894]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -4.25330111]
 [  5.          -5.84042113]
 [ -5.          -1.64381025]
 [-10.           1.64350256]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   5.20882465]
 [  5.33333333   6.93148473]
 [ -5.33333333  -1.923351  ]
 [-10.66666667  -4.45431311]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -3.16385331]
 [  5.33333333  -9.73152519]
 [ -5.33333333   2.02598933]
 [-10.66666667   5.0265699 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           1.01851355]
 [  6.          -2.36282316]
 [ -6.          -1.29166997]
 [-12.           3.16631666]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.          -0.10431215]
 [  6.          -9.62371688]
 [ -6.          -9.98629861]
 [-12.          -2.61738377]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           4.41367547]
 [  6.          -5.57582913]
 [ -6.         -11.60744298]
 [-12.          -0.59162794]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -2.05656186]
 [  5.33333333   7.20577812]
 [ -5.33333333   0.1981273 ]
 [-10.66666667   4.74162991]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           3.03785404]
 [  5.           4.20793893]
 [ -5.          -6.68784135]
 [-10.          -4.32092306]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -6.25390586]
 [  7.           3.85117883]
 [ -7.          -8.64848827]
 [-14.           1.19962825]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   4.89857897]
 [  5.33333333  -7.10243417]
 [ -5.33333333   2.11607492]
 [-10.66666667   0.49374017]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.82842712   2.82842712]
 [ 13.33333333  -3.49988157]
 [  6.66666667  -3.40359545]
 [ -6.66666667   6.00066352]
 [-13.33333333   4.84422383]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-d26a071e78a2>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
