In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random

In [2]:

class ThreeLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.l1 = np.random.randint(2,8)
        self.l2 = np.random.randint(2,8)
        self.l3 = np.random.randint(2,8)

    def forwardKinematics(self, theta1, theta2, theta3):
        # Define the homogeneous transformation matrices for the 3-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], [np.sin(self.theta1), np.cos(self.theta1), 0], [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1], [np.sin(self.theta2), np.cos(self.theta2), 0], [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])        
        self.t3end = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l3], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])
        self.t0end = self.t01*self.t12*self.t23*self.t3end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        # Find the x, y coordinates for joints 2 and 3. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.endEffPos = j2,j3,endeff
        return j2,j3,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2)]).T 
        return J

In [3]:
def plotArm(jnt2pos, jnt3pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, endEffectPos,x2,y2,target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt3pos[0],x2[0]],[jnt3pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt3pos[0],x2[1]],[jnt3pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = ThreeLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, endEffectorPos = init_joint2pos, init_joint3pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len=np.random.randint(2,arm.l3+1)
    
    keypoints_data=pd.DataFrame(columns=range((4+2)*2),dtype=float)

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2])
        joint2pos, joint3pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2] \
                                 +np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2] \
                                 +np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2] \
                                 -np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2] \
                                 -np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motionv9/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((4+2,4+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[2][4]=1
    adj_mat[2][5]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motionv9/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motionv9/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
# create_simulation(7001,50)

In [6]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [7]:
for i in range(375,500):
    create_simulation(i,50)

12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          0.75815333]
 [ 4.          5.52128093]
 [-4.          1.10996765]
 [-8.         -2.89535057]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          1.71338282]
 [ 4.          0.9656855 ]
 [-4.         -7.39554916]
 [-8.          3.2379108 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.12132034  2.12132034]
 [ 7.33333333  3.1278991 ]
 [ 3.66666667 -6.50165878]
 [-3.66666667  6.79425452]
 [-7.33333333  0.61429   ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  3.65337459]
 [ 4.66666667 -8.00541687]
 [-4.66666667  0.4878759 ]
 [-9.33333333 -2.92382547]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.82842712  2.82842712]
 [ 8.66666667 -1.42435307]
 [ 4.33333333  1.952676  ]
 [-4.33333333 -4.96137953]
 [-8.66666667 -4.45010147]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           3.6633994 ]
 [  6.          -1.52865546]
 [ -6.           8.07726868]
 [-12.           0.40680477]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.12132034   2.12132034]
 [ 10.66666667   3.17885858]
 [  5.33333333  -4.03075288]
 [ -5.33333333  -7.3045851 ]
 [-10.66666667   2.469458  ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  3.45748149]
 [ 4.66666667  8.26191143]
 [-4.66666667 -2.17366868]
 [-9.33333333 -1.97180868]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -4.56107856]
 [ 4.66666667 -8.93813642]
 [-4.66666667  1.22407041]
 [-9.33333333 -2.45875758]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -3.56717005]
 [  5.           4.23132951]
 [ -5.           3.2349746 ]
 [-10.           4.76232384]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -5.66952745]
 [  5.66666667  -5.72887074]
 [ -5.66666667   7.19896635]
 [-11.33333333   4.3895222 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -0.62408004]
 [  6.66666667  -9.51992928]
 [ -6.66666667  -4.8114658 ]
 [-13.33333333   4.76451558]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333  -4.27163061]
 [  6.66666667 -11.08376979]
 [ -6.66666667  -9.55859292]
 [-13.33333333   0.72230238]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -0.28270298]
 [ 4.66666667  4.03023314]
 [-4.66666667 -6.54108951]
 [-9.33333333 -4.70181762]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.12132034  2.12132034]
 [ 7.33333333 -2.60825951]
 [ 3.66666667  0.84198702]
 [-3.66666667  5.08613141]
 [-7.33333333  0.10761365]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[13.12132034  2.12132034]
 [ 9.33333333  3.15786859]
 [ 4.66666667  5.69398101]
 [-4.66666667  4.75466723]
 [-9.33333333 -3.2594042 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          2.1222881 ]
 [ 4.          6.56391258]
 [-4.         -5.86781869]
 [-8.         -2.76131786]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.         -3.66019635]
 [ 4.         -4.02165302]
 [-4.         -2.17443545]
 [-8.          2.81737035]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.          -3.08163619]
 [  5.          -8.08975245]
 [ -5.          -8.61837388]
 [-10.          -0.81001015]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333  0.14044249]
 [ 3.66666667  6.99593748]
 [-3.66666667  3.56026013]
 [-7.33333333  1.15209157]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667 -1.84093886]
 [ 4.33333333  8.3842617 ]
 [-4.33333333  0.32684706]
 [-8.66666667 -1.55452402]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.94974747  4.94974747]
 [ 8.         -2.06952195]
 [ 4.          5.22608107]
 [-4.         -5.66571948]
 [-8.         -2.40436006]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -2.59506531]
 [ 4.33333333  6.77993196]
 [-4.33333333 -5.88536503]
 [-8.66666667  0.92694221]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   5.29020286]
 [  5.66666667  -5.29137476]
 [ -5.66666667  -8.11812829]
 [-11.33333333  -4.87442928]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -1.08162918]
 [  6.           1.61013266]
 [ -6.          10.46014245]
 [-12.          -1.98083993]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333 -2.03911249]
 [ 4.66666667 -7.87827535]
 [-4.66666667 -2.44410443]
 [-9.33333333  1.58749947]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.53553391  3.53553391]
 [ 7.33333333 -0.30021076]
 [ 3.66666667  0.9138748 ]
 [-3.66666667 -7.21937066]
 [-7.33333333 -3.46678258]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -3.4678557 ]
 [ 4.33333333 -2.61729569]
 [-4.33333333 -7.58255644]
 [-8.66666667 -4.43012791]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.          1.49269157]
 [ 4.         -4.11294921]
 [-4.         -2.32123401]
 [-8.         -2.48854893]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.         -3.01031277]
 [ 4.          7.11090226]
 [-4.          3.72799072]
 [-8.         -0.04247468]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.94974747  4.94974747]
 [ 8.          2.6349347 ]
 [ 4.         -7.13022255]
 [-4.         -1.32855088]
 [-8.         -0.7500509 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -3.78782026]
 [  6.33333333  -6.80796873]
 [ -6.33333333   3.46314014]
 [-12.66666667  -0.38212048]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333 -2.06711501]
 [ 3.66666667  2.18724968]
 [-3.66666667  2.83217467]
 [-7.33333333 -0.47243972]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.53553391  3.53553391]
 [ 6.66666667 -1.36906641]
 [ 3.33333333  4.3209427 ]
 [-3.33333333 -2.50162019]
 [-6.66666667  1.98907293]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.          3.95914144]
 [ 4.          0.40213171]
 [-4.          4.95382621]
 [-8.          3.33675187]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.         -0.14132783]
 [ 3.          1.85205097]
 [-3.          3.58648234]
 [-6.          2.53918255]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.          -2.86191671]
 [  5.          -0.09959967]
 [ -5.          -2.07522574]
 [-10.           4.45343971]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -0.93879339]
 [ 4.33333333 -0.66655096]
 [-4.33333333 -7.0269299 ]
 [-8.66666667  2.00672067]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           1.00592671]
 [  6.           8.41752793]
 [ -6.          -3.6645419 ]
 [-12.          -2.0826498 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   1.54602826]
 [  5.33333333   8.97439562]
 [ -5.33333333  -8.1497544 ]
 [-10.66666667  -0.23241853]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.         -2.0121677 ]
 [ 4.          5.21268614]
 [-4.          3.29402136]
 [-8.         -4.05885039]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667   0.39598207]
 [  5.33333333   9.18513449]
 [ -5.33333333 -10.49447465]
 [-10.66666667   1.19842356]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.82842712   2.82842712]
 [ 11.33333333   0.65413968]
 [  5.66666667   7.75997333]
 [ -5.66666667   2.52200826]
 [-11.33333333   3.89748317]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


7
The interpolation points are stored in the variable "EF_target_pos": 
[[ 6.41421356  1.41421356]
 [ 4.66666667 -0.86308257]
 [ 2.33333333  0.02004201]
 [-2.33333333  0.19574679]
 [-4.66666667  0.73768554]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -2.46227639]
 [  5.33333333   2.30795418]
 [ -5.33333333  -0.02418021]
 [-10.66666667   4.37234606]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667  3.53626294]
 [ 4.33333333 -6.19531567]
 [-4.33333333  3.63048981]
 [-8.66666667 -0.77678824]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   0.79875328]
 [  5.66666667  10.1776866 ]
 [ -5.66666667  10.82482559]
 [-11.33333333   4.4068581 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          2.76434388]
 [ 4.         -2.79501608]
 [-4.          4.56052445]
 [-8.         -2.54019017]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -3.4107583 ]
 [  6.         -11.36040033]
 [ -6.          -7.58543614]
 [-12.          -3.02802676]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  4.32275078]
 [ 4.66666667 -2.2647697 ]
 [-4.66666667  1.40346024]
 [-9.33333333 -3.04045144]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667 -0.76142494]
 [ 3.33333333  5.18129178]
 [-3.33333333  1.08480718]
 [-6.66666667  2.49074672]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.41421356  1.41421356]
 [ 8.66666667 -2.06455607]
 [ 4.33333333 -2.55057778]
 [-4.33333333  4.15732842]
 [-8.66666667 -1.19541891]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.41213203e+01  2.12132034e+00]
 [ 1.00000000e+01  1.17737889e-02]
 [ 5.00000000e+00  4.65575609e+00]
 [-5.00000000e+00 -3.77080447e+00]
 [-1.00000000e+01 -4.26688819e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   1.99942153]
 [  5.33333333   1.27763499]
 [ -5.33333333  -3.45868473]
 [-10.66666667   1.96991027]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333 -1.35766174]
 [ 4.66666667 -8.3903825 ]
 [-4.66666667  7.06397097]
 [-9.33333333 -1.84185261]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[13.41421356  1.41421356]
 [ 9.33333333 -1.10858302]
 [ 4.66666667 -6.88981556]
 [-4.66666667  7.57809937]
 [-9.33333333 -3.96238199]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.41421356  1.41421356]
 [ 5.33333333  1.99806607]
 [ 2.66666667  4.02635903]
 [-2.66666667  3.18231136]
 [-5.33333333 -2.45893088]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -1.72268623]
 [ 4.33333333  0.4741106 ]
 [-4.33333333 -5.11092565]
 [-8.66666667 -0.95231763]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.82842712  2.82842712]
 [ 6.          2.31696162]
 [ 3.         -2.32115986]
 [-3.          0.2193093 ]
 [-6.          2.27627353]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.         -2.06746481]
 [ 3.          1.25391183]
 [-3.         -5.54340823]
 [-6.         -2.331704  ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.94974747  4.94974747]
 [ 7.33333333  1.28548598]
 [ 3.66666667  3.57185065]
 [-3.66666667 -4.65087652]
 [-7.33333333  2.51681376]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.          -1.39995837]
 [  5.          -8.98671468]
 [ -5.          -5.89759148]
 [-10.           0.83571411]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -2.66848736]
 [  6.           3.81716774]
 [ -6.         -11.45957776]
 [-12.           0.40732105]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           1.60144835]
 [  7.          13.24246508]
 [ -7.         -11.84360813]
 [-14.           3.57866308]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.         -3.85412595]
 [ 4.          7.20482441]
 [-4.          7.11882216]
 [-8.         -0.53077082]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   4.78882192]
 [  5.33333333   1.4712143 ]
 [ -5.33333333  -8.72778059]
 [-10.66666667   0.06698144]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.82842712  2.82842712]
 [ 6.66666667 -1.48100226]
 [ 3.33333333 -4.55079297]
 [-3.33333333 -1.42464207]
 [-6.66666667  2.43253762]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           2.28217702]
 [  5.          -3.63576756]
 [ -5.          -5.11483436]
 [-10.          -4.48745988]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.53553391  3.53553391]
 [ 6.         -1.16292352]
 [ 3.          0.98113123]
 [-3.          0.54710213]
 [-6.          0.15358007]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   3.91550393]
 [  6.33333333  -4.87644848]
 [ -6.33333333   3.74835241]
 [-12.66666667   3.32595494]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.41421356  1.41421356]
 [ 7.33333333 -3.5966737 ]
 [ 3.66666667 -0.13930217]
 [-3.66666667  4.08857416]
 [-7.33333333 -3.42500646]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.          -2.96568368]
 [  5.           9.23463301]
 [ -5.           0.47694895]
 [-10.          -1.34496803]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -4.07049948]
 [ 4.66666667  2.22080184]
 [-4.66666667  8.17744182]
 [-9.33333333 -4.12843236]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   2.42792803]
 [  5.33333333  -3.86903874]
 [ -5.33333333   4.63205134]
 [-10.66666667  -3.88800345]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          3.99138343]
 [ 4.          6.27465718]
 [-4.          1.061932  ]
 [-8.          1.12613956]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 6.82842712  2.82842712]
 [ 5.33333333  2.57413524]
 [ 2.66666667 -3.75685667]
 [-2.66666667 -4.26515745]
 [-5.33333333 -2.00105153]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.         -0.70314145]
 [ 3.          3.71481761]
 [-3.          2.52489951]
 [-6.         -1.19386093]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -5.12034693]
 [  5.33333333  -8.89904361]
 [ -5.33333333   8.64051758]
 [-10.66666667   1.69263316]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           2.73740218]
 [  5.           4.09784969]
 [ -5.          -2.26551909]
 [-10.          -5.11056358]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


8
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.41421356  1.41421356]
 [ 5.33333333  1.14869982]
 [ 2.66666667  3.24686533]
 [-2.66666667  1.91837773]
 [-5.33333333 -2.60047444]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -2.97607154]
 [  5.          -9.52309499]
 [ -5.          -7.61508861]
 [-10.           3.3189373 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  0.68538628]
 [ 4.66666667  9.36350598]
 [-4.66666667 -3.37746497]
 [-9.33333333  2.38139649]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.41421356   1.41421356]
 [ 10.           0.91282186]
 [  5.           8.7068506 ]
 [ -5.          -4.8347708 ]
 [-10.          -4.13263036]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  0.27113102]
 [ 4.66666667 -0.04760186]
 [-4.66666667  4.61896214]
 [-9.33333333  0.53686501]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   3.04932772]
 [  5.33333333   4.2013436 ]
 [ -5.33333333  10.74862434]
 [-10.66666667   4.99141113]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.          -3.38276257]
 [  5.           5.25135954]
 [ -5.           8.61378941]
 [-10.           1.02534528]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -1.80868111]
 [ 4.33333333 -8.2779074 ]
 [-4.33333333  7.20037605]
 [-8.66666667 -0.34598541]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          1.97203673]
 [ 4.          7.34867134]
 [-4.         -2.6041556 ]
 [-8.         -2.75592107]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667  1.8309739 ]
 [ 3.33333333  4.16515121]
 [-3.33333333  2.47024695]
 [-6.66666667 -2.99061789]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   3.67964922]
 [  6.33333333  -3.7262159 ]
 [ -6.33333333   1.8924301 ]
 [-12.66666667   1.33891027]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.41421356  1.41421356]
 [ 7.33333333 -2.44658439]
 [ 3.66666667 -1.29455788]
 [-3.66666667  1.87603818]
 [-7.33333333  3.21821924]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[12.12132034  2.12132034]
 [ 8.66666667 -3.81668203]
 [ 4.33333333 -3.71467319]
 [-4.33333333  4.21135845]
 [-8.66666667  4.38886488]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  0.88640477]
 [ 4.66666667  3.17906429]
 [-4.66666667 -0.74894503]
 [-9.33333333 -2.25372808]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -0.0640534 ]
 [  5.66666667  -0.19104258]
 [ -5.66666667  -8.18767273]
 [-11.33333333  -4.3287732 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.          -4.3388665 ]
 [  5.           1.64411832]
 [ -5.          -4.36878778]
 [-10.           4.86624433]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667 -2.52274794]
 [ 3.33333333  5.48293756]
 [-3.33333333 -1.55284259]
 [-6.66666667  3.19517481]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.          -4.19376506]
 [  7.         -11.1252908 ]
 [ -7.           5.48816449]
 [-14.          -0.40919889]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667   3.8197683 ]
 [  5.33333333   5.4342492 ]
 [ -5.33333333   1.88050395]
 [-10.66666667   4.12681903]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333 -1.15595103]
 [ 4.66666667 -2.97311253]
 [-4.66666667  2.13926561]
 [-9.33333333 -1.24519971]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -2.1291716 ]
 [ 4.66666667 -0.67987905]
 [-4.66666667 -6.18200393]
 [-9.33333333 -2.15119862]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333  0.09541646]
 [ 3.66666667 -5.41421967]
 [-3.66666667 -2.32343415]
 [-7.33333333 -1.64332574]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  0.05242162]
 [ 4.66666667  8.51882863]
 [-4.66666667 -8.29383366]
 [-9.33333333 -1.03733174]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667  1.27316036]
 [ 4.33333333  6.74740378]
 [-4.33333333  0.04868445]
 [-8.66666667  1.52009865]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           3.72074968]
 [  6.           1.46405417]
 [ -6.         -10.7749897 ]
 [-12.           2.21130265]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.41421356   1.41421356]
 [ 10.66666667  -4.78163139]
 [  5.33333333  -8.05455886]
 [ -5.33333333  -5.80620575]
 [-10.66666667   1.42688432]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 8.12132034  2.12132034]
 [ 6.         -1.77553495]
 [ 3.         -1.21758093]
 [-3.         -0.78006348]
 [-6.         -0.80162358]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           0.76093088]
 [  6.           7.85735819]
 [ -6.           7.67686572]
 [-12.          -5.5594738 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.38284271e+01  2.82842712e+00]
 [ 1.00000000e+01 -4.83984574e+00]
 [ 5.00000000e+00  2.87953381e+00]
 [-5.00000000e+00  4.97858772e+00]
 [-1.00000000e+01  6.76634150e-03]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -4.13890428]
 [ 4.66666667 -3.09665497]
 [-4.66666667 -6.92269126]
 [-9.33333333  2.11246498]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[10.12132034  2.12132034]
 [ 7.33333333 -2.8979087 ]
 [ 3.66666667  1.07740553]
 [-3.66666667 -4.89914976]
 [-7.33333333  3.61895615]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667 -2.42767902]
 [ 4.33333333  6.5733993 ]
 [-4.33333333 -1.19724084]
 [-8.66666667  3.35331726]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.41421356  1.41421356]
 [ 8.         -1.52506705]
 [ 4.          8.00713712]
 [-4.         -6.89410504]
 [-8.         -0.53939612]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -3.61703824]
 [ 4.66666667  7.39648719]
 [-4.66666667 -2.92699294]
 [-9.33333333  0.82262743]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.12132034   2.12132034]
 [ 10.          -0.48647913]
 [  5.           3.73506865]
 [ -5.          -1.41241096]
 [-10.          -4.44180458]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          3.52969628]
 [ 4.         -4.79100053]
 [-4.          1.67613034]
 [-8.         -3.7411828 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


10
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.41421356  1.41421356]
 [ 6.66666667  1.06806036]
 [ 3.33333333  1.30263865]
 [-3.33333333  4.41144818]
 [-6.66666667 -0.55136074]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           1.59071628]
 [  5.          -4.69769723]
 [ -5.          -8.32327328]
 [-10.           2.28469495]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333  0.3734352 ]
 [ 3.66666667 -1.62869519]
 [-3.66666667  4.71156437]
 [-7.33333333  1.62442077]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -0.11044873]
 [ 4.66666667 -7.85393955]
 [-4.66666667  1.79089102]
 [-9.33333333  0.51979495]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333 -2.53282498]
 [ 3.66666667  3.65268126]
 [-3.66666667 -0.23770489]
 [-7.33333333  2.64163174]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  2.10651228]
 [ 4.66666667  0.77194757]
 [-4.66666667 -4.51547807]
 [-9.33333333 -3.72868289]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -3.30291544]
 [  6.33333333  -3.49822008]
 [ -6.33333333   2.52284427]
 [-12.66666667   1.697206  ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[11.12132034  2.12132034]
 [ 8.          3.82768116]
 [ 4.         -4.6915295 ]
 [-4.          2.45369006]
 [-8.          1.4088207 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           6.18300939]
 [  6.           1.82302966]
 [ -6.          -9.31973717]
 [-12.          -0.41303675]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   5.36392409]
 [  5.66666667  -2.16544581]
 [ -5.66666667  -7.19840036]
 [-11.33333333  -0.08783427]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
