In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random

In [2]:

class FourLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.theta4 = np.deg2rad(90)
        self.l1 = np.random.randint(2,8)
        self.l2 = np.random.randint(2,8)
        self.l3 = np.random.randint(2,8)
        self.l4 = np.random.randint(2,8)

    def forwardKinematics(self, theta1, theta2, theta3,theta4):
        # Define the homogeneous transformation matrices for the 4-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.theta4 = theta4
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], 
                              [np.sin(self.theta1), np.cos(self.theta1), 0],
                              [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1],
                              [np.sin(self.theta2), np.cos(self.theta2), 0],
                              [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2],
                              [np.sin(self.theta3), np.cos(self.theta3), 0],
                              [0, 0, 1]])        
        self.t34 = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l3],
                              [np.sin(self.theta4), np.cos(self.theta4), 0],
                              [0, 0, 1]])
        self.t4end = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l4],
                                [np.sin(self.theta4), np.cos(self.theta4), 0],
                                [0, 0, 1]])

        self.t0end = self.t01*self.t12*self.t23*self.t34*self.t4end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3 and joint 4
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        self.t04 = self.t01*self.t12*self.t23*self.t34
        # Find the x, y coordinates for joints 2 and 3 and 4. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        j4 = [ self.t04[0, 2], self.t04[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.jnt4pos, self.endEffPos = j2,j3,j4,endeff
        return j2,j3,j4,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, jnt4pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if jnt4pos is None:
            jnt4pos=self.jnt4pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        col3 = np.array(endEffPos + [0]) - np.array(jnt4pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2), np.cross(ai,col3)]).T 
        return J

In [3]:
def plotArm(jnt2pos, jnt3pos, jnt4pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, jnt4pos, endEffectPos,x2,y2, target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt4pos[0],x2[0]],[jnt4pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt4pos[0],x2[1]],[jnt4pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = FourLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45),np.deg2rad(45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3+arm.l4
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, joint4pos, endEffectorPos = init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len=np.random.randint(2,arm.l4+1)
    
    keypoints_data=pd.DataFrame(columns=range((5+2)*2),dtype=float)

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2],newTheta[3])
        joint2pos, joint3pos, joint4pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +arm.l3*np.cos(newTheta[0]+newTheta[1]+newTheta[2]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2]+newTheta[3]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +arm.l3*np.sin(newTheta[0]+newTheta[1]+newTheta[2]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2]+newTheta[3]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
        
        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +arm.l3*np.cos(newTheta[0]+newTheta[1]+newTheta[2]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2]+newTheta[3]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +arm.l3*np.sin(newTheta[0]+newTheta[1]+newTheta[2]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2]+newTheta[3]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],joint4pos[0],joint4pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, joint4pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motionv9/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((5+2,5+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[3][4]=1
    adj_mat[3][5]=1
    adj_mat[3][6]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motionv9/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motionv9/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
# create_simulation(8005,50)

In [6]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [7]:
for i in range(625,750):
    create_simulation(i,50)

13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667  3.00026116]
 [ 4.33333333  2.96009359]
 [-4.33333333  2.4378673 ]
 [-8.66666667 -3.89176609]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   0.94930942]
 [  5.66666667   6.66167549]
 [ -5.66666667   5.02247094]
 [-11.33333333   0.54108624]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          3.31179188]
 [ 4.         -1.83332236]
 [-4.          1.19096284]
 [-8.         -0.10854181]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   6.11514822]
 [  6.33333333  -2.76702297]
 [ -6.33333333  -4.29922804]
 [-12.66666667  -3.72433665]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


25
The interpolation points are stored in the variable "EF_target_pos": 
[[ 2.17781746e+01  7.77817459e+00]
 [ 1.66666667e+01  1.54941988e-02]
 [ 8.33333333e+00 -3.80717516e+00]
 [-8.33333333e+00 -7.02919998e+00]
 [-1.66666667e+01  6.96389278e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.48528137   8.48528137]
 [ 11.33333333  -2.2861683 ]
 [  5.66666667   2.61225251]
 [ -5.66666667   6.72223746]
 [-11.33333333   1.23109715]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.89949494   9.89949494]
 [ 15.33333333  -3.47670466]
 [  7.66666667 -14.74937579]
 [ -7.66666667   4.72841364]
 [-15.33333333  -3.49968413]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           5.39839352]
 [  7.           1.15840807]
 [ -7.          -7.90358882]
 [-14.          -3.25800334]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.36396103   6.36396103]
 [ 14.66666667  -3.99811488]
 [  7.33333333   2.77987935]
 [ -7.33333333  13.25724883]
 [-14.66666667  -2.43915181]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   6.48624261]
 [  6.66666667  -7.0096681 ]
 [ -6.66666667   6.52159344]
 [-13.33333333   6.34408517]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.77817459   7.77817459]
 [ 11.33333333   4.00388889]
 [  5.66666667  -0.97667166]
 [ -5.66666667  -9.1944007 ]
 [-11.33333333   0.60469087]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.77817459   7.77817459]
 [ 13.33333333  -2.98621923]
 [  6.66666667   7.34266203]
 [ -6.66666667 -12.78210507]
 [-13.33333333   6.45470028]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -6.86246432]
 [  7.33333333  -8.46965827]
 [ -7.33333333  10.48627785]
 [-14.66666667   4.09206955]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.89949494   9.89949494]
 [ 17.33333333  -7.87210589]
 [  8.66666667 -13.18770742]
 [ -8.66666667   2.38722694]
 [-17.33333333   0.60427144]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.71923882e+01  9.19238816e+00]
 [ 1.40000000e+01  5.62564400e+00]
 [ 7.00000000e+00 -5.05713572e+00]
 [-7.00000000e+00  2.16600245e-03]
 [-1.40000000e+01 -6.76471713e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           4.97767008]
 [  6.          -4.11476213]
 [ -6.         -11.18599632]
 [-12.          -2.03805255]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333   4.61631982]
 [  5.66666667   3.14809908]
 [ -5.66666667  -7.62639458]
 [-11.33333333  -2.58432567]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.36396103  6.36396103]
 [ 8.66666667 -1.22662535]
 [ 4.33333333 -5.88669375]
 [-4.33333333  5.05983239]
 [-8.66666667 -0.05526852]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.07106781  7.07106781]
 [ 9.33333333  3.25578321]
 [ 4.66666667 -5.13728469]
 [-4.66666667  2.54587626]
 [-9.33333333  0.55275406]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   4.5581296 ]
 [  5.33333333  10.14523937]
 [ -5.33333333   0.39037563]
 [-10.66666667   4.0496215 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.71923882e+01  9.19238816e+00]
 [ 1.40000000e+01 -4.65386720e-01]
 [ 7.00000000e+00 -1.25687191e+00]
 [-7.00000000e+00 -3.67396790e+00]
 [-1.40000000e+01 -9.28813629e-03]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.77817459   7.77817459]
 [ 14.66666667   5.75130881]
 [  7.33333333  -6.04618432]
 [ -7.33333333   9.45477743]
 [-14.66666667   0.38186606]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333   5.57174364]
 [  5.66666667  -4.02685188]
 [ -5.66666667   0.5926413 ]
 [-11.33333333  -4.28127151]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 22.19238816   9.19238816]
 [ 17.33333333  -4.90160307]
 [  8.66666667 -10.55202189]
 [ -8.66666667  10.81849136]
 [-17.33333333  -4.24665052]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.48528137   8.48528137]
 [ 16.          -0.20412492]
 [  8.           8.79032258]
 [ -8.           4.16278226]
 [-16.          -6.39629384]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  1.26739735]
 [ 4.33333333 -5.55133922]
 [-4.33333333 -8.22527373]
 [-8.66666667 -0.59822271]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -3.38386109]
 [  5.33333333   2.50595361]
 [ -5.33333333  -4.69978262]
 [-10.66666667  -4.61966327]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.48528137   8.48528137]
 [ 12.          -3.85833341]
 [  6.           2.76336098]
 [ -6.           3.72908189]
 [-12.           4.54515071]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.65685425   5.65685425]
 [ 10.           3.33401173]
 [  5.         -10.06604876]
 [ -5.           5.10187692]
 [-10.           4.05483637]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.36396103   6.36396103]
 [ 12.66666667   6.24135968]
 [  6.33333333  -3.30105535]
 [ -6.33333333  12.56554577]
 [-12.66666667   1.96761804]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333  0.11457936]
 [ 3.66666667  4.14921743]
 [-3.66666667 -4.94457971]
 [-7.33333333 -3.11326235]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.65685425   5.65685425]
 [ 10.66666667  -1.35534654]
 [  5.33333333  -4.52719135]
 [ -5.33333333  -7.75385807]
 [-10.66666667  -1.9609642 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           1.20708029]
 [  5.           6.17847288]
 [ -5.          -3.49368996]
 [-10.          -2.6281034 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -2.25832227]
 [  7.33333333   0.44733938]
 [ -7.33333333 -10.49595082]
 [-14.66666667   0.71448516]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   4.24569751]
 [  6.66666667  -5.8757686 ]
 [ -6.66666667  -7.01625223]
 [-13.33333333  -5.24478268]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.65685425  5.65685425]
 [ 9.33333333 -3.963121  ]
 [ 4.66666667  0.42366547]
 [-4.66666667 -2.67336185]
 [-9.33333333 -4.05190432]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -3.12107776]
 [  5.           7.51918375]
 [ -5.          -4.06228899]
 [-10.           2.02442196]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.07106781   7.07106781]
 [ 16.          -7.00022418]
 [  8.          -8.06526825]
 [ -8.           7.89815506]
 [-16.          -5.71936364]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -5.7536591 ]
 [  5.66666667  -7.67673767]
 [ -5.66666667  -8.74132024]
 [-11.33333333   2.63664699]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -2.46429148]
 [  5.66666667  -0.49609797]
 [ -5.66666667   4.4138679 ]
 [-11.33333333  -1.91787394]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   3.51425847]
 [  5.66666667  -4.91125456]
 [ -5.66666667  -4.99134431]
 [-11.33333333   2.09604369]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.48528137   8.48528137]
 [ 12.           5.9652228 ]
 [  6.          -2.0081669 ]
 [ -6.          11.10587498]
 [-12.           3.77650645]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  1.63270627]
 [ 4.66666667  9.26992559]
 [-4.66666667 -5.65828871]
 [-9.33333333  1.08486386]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.66568542e+01  5.65685425e+00]
 [ 1.26666667e+01 -1.02263279e-02]
 [ 6.33333333e+00  9.96852998e+00]
 [-6.33333333e+00 -1.06951764e+00]
 [-1.26666667e+01 -1.23476979e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   1.23976668]
 [  6.33333333   0.27416387]
 [ -6.33333333   2.27765656]
 [-12.66666667   4.06315327]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.          -1.88732106]
 [  6.           7.78286594]
 [ -6.           2.44375685]
 [-12.          -2.21400479]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.36396103  6.36396103]
 [ 9.33333333 -1.70519893]
 [ 4.66666667 -5.98848914]
 [-4.66666667 -7.8360751 ]
 [-9.33333333 -2.29670169]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   0.90788369]
 [  6.33333333  -8.16530302]
 [ -6.33333333 -10.17511612]
 [-12.66666667  -0.39653889]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   3.89305275]
 [  5.33333333  -0.49704371]
 [ -5.33333333   6.9859849 ]
 [-10.66666667  -5.25757922]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.48528137   8.48528137]
 [ 16.           7.95762171]
 [  8.           5.9943806 ]
 [ -8.           0.37572144]
 [-16.           7.64440976]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.          -2.27145922]
 [  5.           2.63623446]
 [ -5.          -4.08118529]
 [-10.           1.91474897]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.65685425   5.65685425]
 [ 10.          -2.71814219]
 [  5.          -6.42905839]
 [ -5.           1.75279383]
 [-10.           3.01362266]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.36396103   6.36396103]
 [ 10.          -2.50580861]
 [  5.           6.77537394]
 [ -5.           1.00241714]
 [-10.           3.87497923]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333 -4.00677608]
 [ 4.66666667 -8.08174088]
 [-4.66666667 -2.78601075]
 [-9.33333333  1.03057033]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.07106781   7.07106781]
 [ 10.           5.12739839]
 [  5.          -7.13457324]
 [ -5.           4.79234209]
 [-10.          -4.89612229]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.19238816   9.19238816]
 [ 13.33333333  -2.13270307]
 [  6.66666667   3.07075878]
 [ -6.66666667   5.6931776 ]
 [-13.33333333  -3.59308204]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -5.30298025]
 [  7.          13.31498007]
 [ -7.           3.02230622]
 [-14.           3.89556327]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.98245003]
 [  6.33333333   5.33620899]
 [ -6.33333333  10.56639108]
 [-12.66666667  -3.29007754]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.19238816   9.19238816]
 [ 14.           3.99258034]
 [  7.           3.15402259]
 [ -7.          10.34128947]
 [-14.           6.67572131]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.36396103   6.36396103]
 [ 13.33333333   3.25463889]
 [  6.66666667  -1.24316608]
 [ -6.66666667  -0.38878046]
 [-13.33333333  -0.54165947]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.36396103   6.36396103]
 [ 10.          -3.55401931]
 [  5.          -5.03025133]
 [ -5.           6.16825971]
 [-10.          -3.31013864]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -4.52048172]
 [  6.          -0.94991376]
 [ -6.           5.09466428]
 [-12.          -1.78682571]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 11.77817459   7.77817459]
 [ 10.           4.47450884]
 [  5.           3.52426011]
 [ -5.           2.60955754]
 [-10.          -3.95447997]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           5.79040132]
 [  6.          -7.31684393]
 [ -6.           6.74559159]
 [-12.          -1.58091505]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.           1.82911144]
 [  6.          -3.90299805]
 [ -6.          -1.58000956]
 [-12.           2.40325334]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -2.2218331 ]
 [  5.66666667   5.84589423]
 [ -5.66666667   6.61920703]
 [-11.33333333  -2.59840671]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.07106781   7.07106781]
 [ 10.          -0.54883386]
 [  5.          10.05644529]
 [ -5.           4.14272873]
 [-10.           2.39830789]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.36396103   6.36396103]
 [ 10.66666667  -1.41649113]
 [  5.33333333  -4.91087079]
 [ -5.33333333   4.49087807]
 [-10.66666667  -3.16775298]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.48528137   8.48528137]
 [ 10.66666667   0.78940914]
 [  5.33333333   9.18876102]
 [ -5.33333333   0.69625156]
 [-10.66666667  -4.57484909]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -2.23505252]
 [  5.66666667   5.19546215]
 [ -5.66666667   8.11752212]
 [-11.33333333  -0.62942042]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.          -1.01231227]
 [  5.           6.98590733]
 [ -5.          -0.35843344]
 [-10.          -2.45836111]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   5.84164432]
 [  6.33333333   0.25287917]
 [ -6.33333333  -0.32228916]
 [-12.66666667  -5.36846305]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -3.06853403]
 [  6.           9.18318233]
 [ -6.          11.4975761 ]
 [-12.           3.29994928]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   4.67376546]
 [  6.66666667   9.48650576]
 [ -6.66666667  12.82763316]
 [-13.33333333   1.79735049]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.          -5.96438288]
 [  7.           4.18437383]
 [ -7.           3.51029045]
 [-14.           1.83620751]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333 -3.46607788]
 [ 4.66666667 -3.15745291]
 [-4.66666667  2.74619685]
 [-9.33333333  0.49558249]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.19238816   9.19238816]
 [ 15.33333333  -3.17113101]
 [  7.66666667 -12.41351983]
 [ -7.66666667  -7.11700643]
 [-15.33333333  -7.64548361]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.           5.93887365]
 [  6.          11.53551557]
 [ -6.           6.51930673]
 [-12.           4.84128199]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -2.41961161]
 [  5.33333333   1.82736561]
 [ -5.33333333   2.57056156]
 [-10.66666667  -1.46711378]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333  -1.34003373]
 [  6.66666667  11.38147393]
 [ -6.66666667   9.95630523]
 [-13.33333333   4.15354346]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.77817459   7.77817459]
 [ 13.33333333   6.65086907]
 [  6.66666667  13.32909097]
 [ -6.66666667 -10.65990547]
 [-13.33333333  -5.0335364 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333   5.52994909]
 [  5.66666667  -9.47812084]
 [ -5.66666667   6.17418094]
 [-11.33333333   2.02280921]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333  0.28071679]
 [ 3.66666667 -3.70175107]
 [-3.66666667  1.48441666]
 [-7.33333333 -3.30805127]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   3.99073655]
 [  6.33333333  -6.39800988]
 [ -6.33333333 -11.96481953]
 [-12.66666667  -0.10978537]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.           2.92558069]
 [  6.           0.44536119]
 [ -6.           6.70114206]
 [-12.           5.11562535]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   2.69317092]
 [  6.66666667 -11.59536344]
 [ -6.66666667   5.24751327]
 [-13.33333333  -0.39441946]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667  3.1209502 ]
 [ 4.33333333 -4.87336387]
 [-4.33333333  2.05736352]
 [-8.66666667  3.45663115]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.           1.65235103]
 [  5.           7.42836802]
 [ -5.          -5.23157634]
 [-10.          -4.56004533]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.82842712  2.82842712]
 [ 6.         -2.74974982]
 [ 3.         -1.92323798]
 [-3.         -3.27715185]
 [-6.          1.00691863]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           2.83038952]
 [  6.          -1.31046981]
 [ -6.           0.69861231]
 [-12.           4.5604595 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   2.04309905]
 [  5.33333333   6.5287964 ]
 [ -5.33333333   2.30833717]
 [-10.66666667   2.18570618]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.77817459   7.77817459]
 [ 14.66666667   0.9349096 ]
 [  7.33333333 -10.82561647]
 [ -7.33333333 -13.1251309 ]
 [-14.66666667   3.13459972]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


28
The interpolation points are stored in the variable "EF_target_pos": 
[[ 23.89949494   9.89949494]
 [ 18.66666667  -4.58509842]
 [  9.33333333   6.20607202]
 [ -9.33333333   7.01856104]
 [-18.66666667  -2.7027852 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           0.17450506]
 [  6.         -11.43670331]
 [ -6.           9.27175858]
 [-12.          -5.15583276]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.36396103   6.36396103]
 [ 10.           4.01353111]
 [  5.          -4.33507826]
 [ -5.          -5.80667348]
 [-10.           2.4645418 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           3.35945384]
 [  7.          -9.53691248]
 [ -7.           0.58998123]
 [-14.           2.35727652]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.36396103   6.36396103]
 [ 14.66666667   7.16134662]
 [  7.33333333   8.27293107]
 [ -7.33333333  -6.40964262]
 [-14.66666667   1.75164121]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.           3.62128226]
 [  6.          -1.40093256]
 [ -6.          -0.21166363]
 [-12.           3.88441027]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -1.13583432]
 [  7.           3.93031304]
 [ -7.         -11.27444694]
 [-14.          -6.43517437]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           5.72463417]
 [  6.           4.02703054]
 [ -6.          -5.34794797]
 [-12.          -4.89562527]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.19238816   9.19238816]
 [ 14.          -2.32382244]
 [  7.           1.50970171]
 [ -7.         -10.85813733]
 [-14.           3.04388532]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.          -1.67368192]
 [  7.           6.74928312]
 [ -7.         -10.9845964 ]
 [-14.          -6.10173043]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.53553391  3.53553391]
 [ 6.          1.93204731]
 [ 3.          4.20162939]
 [-3.         -5.78031741]
 [-6.          2.72224706]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.           6.14657991]
 [  7.          -2.60248439]
 [ -7.          -9.39901122]
 [-14.          -5.60437835]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.65685425   5.65685425]
 [ 10.66666667   3.62947489]
 [  5.33333333  -0.40209734]
 [ -5.33333333  -0.11607467]
 [-10.66666667   3.85779365]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -2.52212495]
 [ 4.33333333 -4.71145192]
 [-4.33333333 -4.95301988]
 [-8.66666667 -4.15451739]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.07106781   7.07106781]
 [ 14.66666667  -1.41019652]
 [  7.33333333   0.89568151]
 [ -7.33333333  14.5238618 ]
 [-14.66666667  -4.7994038 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 22.48528137   8.48528137]
 [ 17.33333333  -2.70571984]
 [  8.66666667   9.3552227 ]
 [ -8.66666667  -5.39664213]
 [-17.33333333  -7.93206314]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.36396103   6.36396103]
 [ 14.66666667   2.81022875]
 [  7.33333333  10.12888621]
 [ -7.33333333   2.70550071]
 [-14.66666667  -6.22529582]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          0.71455949]
 [ 4.         -1.31953014]
 [-4.          0.47329498]
 [-8.         -4.10008391]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   6.20053402]
 [  6.33333333   0.96910453]
 [ -6.33333333   7.48228429]
 [-12.66666667  -4.47148812]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.19238816   9.19238816]
 [ 13.33333333   2.06256396]
 [  6.66666667   0.97473927]
 [ -6.66666667   8.22703578]
 [-13.33333333   0.5710294 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.65685425  5.65685425]
 [ 8.66666667  4.13719926]
 [ 4.33333333  6.01886685]
 [-4.33333333 -0.14096904]
 [-8.66666667 -3.6257566 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.         -3.69325063]
 [ 4.         -6.54748233]
 [-4.         -6.34971526]
 [-8.         -0.90386907]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 22.19238816   9.19238816]
 [ 17.33333333  -6.46140376]
 [  8.66666667  15.32268155]
 [ -8.66666667 -11.27471549]
 [-17.33333333   7.78540099]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.          -3.68722464]
 [  6.          -0.43537828]
 [ -6.           3.31074634]
 [-12.          -6.01301279]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.89949494   9.89949494]
 [ 15.33333333  -3.17776033]
 [  7.66666667  14.89415535]
 [ -7.66666667  14.49001101]
 [-15.33333333   1.13433145]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -4.0604785 ]
 [  5.66666667 -10.0249473 ]
 [ -5.66666667   4.42177261]
 [-11.33333333   2.47215966]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          1.36000889]
 [ 4.          3.01468817]
 [-4.         -0.14458633]
 [-8.         -3.73118839]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   0.89485392]
 [  5.66666667   1.36439553]
 [ -5.66666667  -6.35601228]
 [-11.33333333   1.44868933]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -5.20776986]
 [  7.          -4.11824899]
 [ -7.         -14.03187617]
 [-14.          -3.23595231]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333  -3.39171587]
 [  6.66666667   5.92069247]
 [ -6.66666667  -7.5108738 ]
 [-13.33333333   6.77243754]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.         -1.4617156 ]
 [ 4.         -4.29651105]
 [-4.          5.33380827]
 [-8.         -3.86888927]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           2.5521548 ]
 [  7.           0.74399741]
 [ -7.           0.56400716]
 [-14.          -7.11957704]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.19238816   9.19238816]
 [ 14.66666667   1.99489822]
 [  7.33333333  -7.88525216]
 [ -7.33333333  -5.14776192]
 [-14.66666667   5.89359637]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-eda05cffcd9b>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
