In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random

In [2]:

class FourLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.theta4 = np.deg2rad(90)
        self.l1 = np.random.randint(2,8)
        self.l2 = np.random.randint(2,8)
        self.l3 = np.random.randint(2,8)
        self.l4 = np.random.randint(2,8)

    def forwardKinematics(self, theta1, theta2, theta3,theta4):
        # Define the homogeneous transformation matrices for the 4-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.theta4 = theta4
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], 
                              [np.sin(self.theta1), np.cos(self.theta1), 0],
                              [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1],
                              [np.sin(self.theta2), np.cos(self.theta2), 0],
                              [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2],
                              [np.sin(self.theta3), np.cos(self.theta3), 0],
                              [0, 0, 1]])        
        self.t34 = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l3],
                              [np.sin(self.theta4), np.cos(self.theta4), 0],
                              [0, 0, 1]])
        self.t4end = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l4],
                                [np.sin(self.theta4), np.cos(self.theta4), 0],
                                [0, 0, 1]])

        self.t0end = self.t01*self.t12*self.t23*self.t34*self.t4end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3 and joint 4
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        self.t04 = self.t01*self.t12*self.t23*self.t34
        # Find the x, y coordinates for joints 2 and 3 and 4. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        j4 = [ self.t04[0, 2], self.t04[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.jnt4pos, self.endEffPos = j2,j3,j4,endeff
        return j2,j3,j4,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, jnt4pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if jnt4pos is None:
            jnt4pos=self.jnt4pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        col3 = np.array(endEffPos + [0]) - np.array(jnt4pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2), np.cross(ai,col3)]).T 
        return J

In [3]:
def plotArm(jnt2pos, jnt3pos, jnt4pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, jnt4pos, endEffectPos,x2,y2, target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt2pos[0],x2[0]],[jnt2pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt2pos[0],x2[1]],[jnt2pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = FourLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45),np.deg2rad(45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3+arm.l4
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, joint4pos, endEffectorPos = init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len=np.random.randint(2,arm.l2+1)
    
    keypoints_data=pd.DataFrame(columns=range((5+2)*2),dtype=float)

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2],newTheta[3])
        joint2pos, joint3pos, joint4pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
        
        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],joint4pos[0],joint4pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, joint4pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motionv9/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((5+2,5+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[3][4]=1
    adj_mat[1][5]=1
    adj_mat[1][6]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motionv9/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motionv9/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
# create_simulation(8007,50)

In [6]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [7]:
for i in range(875,1000):
    create_simulation(i,50)

20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   6.2239352 ]
 [  6.66666667  10.41573581]
 [ -6.66666667  -2.94460677]
 [-13.33333333  -0.64646997]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.19238816   9.19238816]
 [ 16.           3.5431637 ]
 [  8.         -10.93859122]
 [ -8.           9.40490362]
 [-16.           0.97570734]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           3.70173996]
 [  6.           2.59904589]
 [ -6.          -8.66649158]
 [-12.          -1.69118536]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.          -1.20349471]
 [  6.           5.98866497]
 [ -6.           9.72010024]
 [-12.           2.72256149]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.48528137   8.48528137]
 [ 12.66666667  -3.48454739]
 [  6.33333333  11.62297672]
 [ -6.33333333   5.45568493]
 [-12.66666667  -1.47986731]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333  -4.8045225 ]
 [  5.66666667   9.82672049]
 [ -5.66666667   4.65278374]
 [-11.33333333   0.83074717]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.48528137   8.48528137]
 [ 16.          -0.05041489]
 [  8.           0.50387641]
 [ -8.          11.08752289]
 [-16.          -3.97422441]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.07106781   7.07106781]
 [ 14.66666667   4.82774172]
 [  7.33333333  -0.53162288]
 [ -7.33333333  -1.11508307]
 [-14.66666667  -2.89950138]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.19238816   9.19238816]
 [ 12.           5.99843868]
 [  6.          -2.17880373]
 [ -6.           5.54052857]
 [-12.           3.35102739]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333  -4.18331934]
 [  5.66666667  -0.35088657]
 [ -5.66666667  -6.16074628]
 [-11.33333333   2.39775446]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           5.61668892]
 [  7.          -8.01083142]
 [ -7.          -3.54582535]
 [-14.          -4.25442554]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -0.891145  ]
 [  5.66666667  -2.19990911]
 [ -5.66666667  -4.07617277]
 [-11.33333333  -1.6092827 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   3.83749153]
 [  5.66666667   0.2989382 ]
 [ -5.66666667   7.41267213]
 [-11.33333333  -0.48052816]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333 -4.35952247]
 [ 4.66666667 -1.36913998]
 [-4.66666667 -5.26470602]
 [-9.33333333 -0.38180535]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.48528137   8.48528137]
 [ 12.          -5.01578508]
 [  6.          -6.02506695]
 [ -6.          -9.92132672]
 [-12.           4.59686812]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   1.61859282]
 [  5.33333333   3.81001589]
 [ -5.33333333   7.99407498]
 [-10.66666667  -1.18544977]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           2.07142114]
 [  5.          -8.97083573]
 [ -5.           4.97431038]
 [-10.          -2.95086735]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          0.61802132]
 [ 4.          4.10469469]
 [-4.         -1.65612478]
 [-8.         -0.80049566]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -3.23351754]
 [  5.          -8.46037016]
 [ -5.          -4.1805191 ]
 [-10.          -2.40926403]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -3.51735052]
 [  6.           6.83478272]
 [ -6.           2.76081271]
 [-12.           5.92153575]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667  -2.54335467]
 [  6.33333333   9.18355996]
 [ -6.33333333   5.8402342 ]
 [-12.66666667  -2.02862978]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667  -5.071828  ]
 [  6.33333333   2.5032112 ]
 [ -6.33333333  -6.97124165]
 [-12.66666667  -6.02891078]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.65685425  5.65685425]
 [ 9.33333333 -0.39094495]
 [ 4.66666667 -1.73928711]
 [-4.66666667 -6.25730882]
 [-9.33333333 -4.10010678]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.36396103   6.36396103]
 [ 12.66666667  -6.19620396]
 [  6.33333333  11.92098256]
 [ -6.33333333  -2.10048676]
 [-12.66666667  -1.18014344]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -3.62923118]
 [ 4.66666667 -0.97420496]
 [-4.66666667  2.27517483]
 [-9.33333333 -2.21993105]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.           3.05915641]
 [  6.          -8.63772259]
 [ -6.           5.18120307]
 [-12.          -2.38660604]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


9
The interpolation points are stored in the variable "EF_target_pos": 
[[ 7.53553391  3.53553391]
 [ 6.         -2.77592281]
 [ 3.         -2.04594453]
 [-3.         -6.04514721]
 [-6.          0.20005592]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


25
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.77817459   7.77817459]
 [ 16.66666667   1.74151114]
 [  8.33333333   1.58875157]
 [ -8.33333333   0.5269224 ]
 [-16.66666667   0.83745538]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -2.30675387]
 [  5.33333333  -8.02972767]
 [ -5.33333333   0.25158256]
 [-10.66666667   0.13577529]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


25
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.48528137   8.48528137]
 [ 16.66666667   1.29604483]
 [  8.33333333   4.07800857]
 [ -8.33333333   0.36129686]
 [-16.66666667   6.29281437]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.36396103   6.36396103]
 [ 10.          -4.13848801]
 [  5.           4.71149291]
 [ -5.          -8.22857252]
 [-10.          -0.29463635]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           6.97113213]
 [  7.         -13.1744044 ]
 [ -7.          11.56364097]
 [-14.          -3.55839634]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333 -1.26480882]
 [ 3.66666667  2.00552384]
 [-3.66666667 -2.42498094]
 [-7.33333333 -3.25278562]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.         -1.19144626]
 [ 4.          3.2762362 ]
 [-4.          8.02620342]
 [-8.         -0.55230105]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          0.39859943]
 [ 4.          5.35151999]
 [-4.         -2.00820732]
 [-8.          0.8939899 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           0.6334148 ]
 [  6.           8.48574973]
 [ -6.          -9.0887455 ]
 [-12.          -1.92668902]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333  -3.37359827]
 [  5.66666667  -9.54099958]
 [ -5.66666667   4.94636575]
 [-11.33333333  -5.67763184]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333   4.41945626]
 [  5.66666667  -1.5502005 ]
 [ -5.66666667   2.00292816]
 [-11.33333333   0.53250313]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           2.32425246]
 [  7.         -13.86844365]
 [ -7.           4.70597434]
 [-14.          -6.88052368]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333   0.18498874]
 [  5.66666667  -6.29962643]
 [ -5.66666667  -3.07671842]
 [-11.33333333   3.25044906]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.07106781   7.07106781]
 [ 10.          -0.55812246]
 [  5.           7.90894963]
 [ -5.           0.18021312]
 [-10.           1.96373532]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.89949494   9.89949494]
 [ 16.           1.9934026 ]
 [  8.          -4.53308347]
 [ -8.          10.73028772]
 [-16.           6.11600976]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.07106781   7.07106781]
 [ 15.33333333  -4.6019607 ]
 [  7.66666667 -12.46660698]
 [ -7.66666667   5.64249747]
 [-15.33333333   3.71852309]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -5.24965095]
 [  5.33333333   1.49156656]
 [ -5.33333333  -0.62300775]
 [-10.66666667  -2.51904009]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


25
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.19238816   9.19238816]
 [ 16.66666667   6.91803604]
 [  8.33333333  11.20079492]
 [ -8.33333333   7.67074479]
 [-16.66666667  -8.15130182]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333  -1.59109308]
 [  5.66666667  -3.02835761]
 [ -5.66666667 -10.3943182 ]
 [-11.33333333  -5.76002993]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.77817459   7.77817459]
 [ 14.66666667   6.28976714]
 [  7.33333333  -4.4642398 ]
 [ -7.33333333   8.06588491]
 [-14.66666667   3.02863888]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.19238816   9.19238816]
 [ 13.33333333   4.81917506]
 [  6.66666667   0.78661883]
 [ -6.66666667  -2.52726211]
 [-13.33333333   6.09266749]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.         -2.90723669]
 [ 4.          2.23649543]
 [-4.         -6.07630438]
 [-8.         -0.60770582]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   5.13967786]
 [  6.33333333   0.30390792]
 [ -6.33333333   8.29060101]
 [-12.66666667   3.97142003]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.36396103   6.36396103]
 [ 14.66666667   0.10877814]
 [  7.33333333   6.78289997]
 [ -7.33333333  10.10868226]
 [-14.66666667  -5.83219056]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.19238816   9.19238816]
 [ 15.33333333   0.97643932]
 [  7.66666667  -2.18208389]
 [ -7.66666667  11.40495443]
 [-15.33333333   0.97897319]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.65685425  5.65685425]
 [ 8.66666667 -3.00550743]
 [ 4.33333333 -3.71695477]
 [-4.33333333  3.16387668]
 [-8.66666667  0.20392953]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   4.98888739]
 [  5.66666667  -0.19819607]
 [ -5.66666667   7.1859301 ]
 [-11.33333333   5.73598846]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -1.95894503]
 [  5.33333333   8.05314201]
 [ -5.33333333   4.30654502]
 [-10.66666667  -3.30721347]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           6.82211434]
 [  7.          -7.99165841]
 [ -7.           2.90859058]
 [-14.          -0.15668467]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333  -2.74360705]
 [  5.66666667   6.419242  ]
 [ -5.66666667   1.4500216 ]
 [-11.33333333   1.30863684]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.48528137   8.48528137]
 [ 14.          -5.32309044]
 [  7.           7.36617362]
 [ -7.         -10.85714231]
 [-14.           7.14068013]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.36396103   6.36396103]
 [ 12.66666667  -2.09162865]
 [  6.33333333  -3.8212562 ]
 [ -6.33333333   6.98850543]
 [-12.66666667   6.12552875]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   6.08476331]
 [  6.33333333   1.45897901]
 [ -6.33333333  10.22498892]
 [-12.66666667   1.67520281]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.77817459   7.77817459]
 [ 10.66666667   1.34205387]
 [  5.33333333  -0.99709743]
 [ -5.33333333  -9.35421609]
 [-10.66666667  -3.04012085]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -3.18010508]
 [  7.33333333   1.67573512]
 [ -7.33333333   2.61067749]
 [-14.66666667   4.57585   ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.48528137   8.48528137]
 [ 10.66666667   0.20472355]
 [  5.33333333  -2.18260932]
 [ -5.33333333  -8.82556001]
 [-10.66666667   1.47232673]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.07106781  7.07106781]
 [ 9.33333333 -3.13979052]
 [ 4.66666667  3.80312664]
 [-4.66666667 -2.55285283]
 [-9.33333333  4.70952604]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   5.17259704]
 [  5.33333333   1.96523839]
 [ -5.33333333  -7.4270973 ]
 [-10.66666667   4.38502691]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.           5.70752024]
 [  6.           1.51249253]
 [ -6.           4.71908305]
 [-12.           3.32258468]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.          -3.73922592]
 [  7.           8.0435863 ]
 [ -7.           4.07124067]
 [-14.          -6.8762446 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333  -0.79190122]
 [  6.66666667  -5.39509502]
 [ -6.66666667  -6.1264888 ]
 [-13.33333333   5.25552546]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           6.0384317 ]
 [  7.          -0.46456392]
 [ -7.          -0.55922222]
 [-14.          -1.74292821]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.48528137   8.48528137]
 [ 16.          -6.27115507]
 [  8.           0.80787805]
 [ -8.          -7.73883339]
 [-16.          -4.33641766]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.         -2.56404828]
 [ 4.          4.99075111]
 [-4.          7.77799878]
 [-8.         -1.07316653]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.65685425  5.65685425]
 [ 8.         -0.74051055]
 [ 4.          0.47311285]
 [-4.          6.0042992 ]
 [-8.          3.94594176]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   1.43367016]
 [  6.33333333   1.42265126]
 [ -6.33333333  12.00872741]
 [-12.66666667   4.20453721]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          0.21867311]
 [ 4.         -4.37404757]
 [-4.          2.90699974]
 [-8.         -3.01503974]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667  -2.2656832 ]
 [  6.33333333   9.788922  ]
 [ -6.33333333   5.79070875]
 [-12.66666667   2.08631395]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333  -2.75102382]
 [  5.66666667   4.38773742]
 [ -5.66666667   6.63408269]
 [-11.33333333  -0.86723346]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.           3.96716373]
 [  7.           2.7178915 ]
 [ -7.          -0.17794692]
 [-14.           0.67362797]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.89949494   9.89949494]
 [ 14.66666667   6.24997963]
 [  7.33333333  -1.79616297]
 [ -7.33333333  13.56620825]
 [-14.66666667   4.96563631]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   0.28173382]
 [  6.33333333   6.27591425]
 [ -6.33333333   7.0306595 ]
 [-12.66666667  -3.07570806]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.89949494   9.89949494]
 [ 16.           7.46394428]
 [  8.           8.88622702]
 [ -8.         -10.03790212]
 [-16.          -3.24740739]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.65685425   5.65685425]
 [ 10.66666667   2.4460605 ]
 [  5.33333333  -1.35207122]
 [ -5.33333333   1.60881548]
 [-10.66666667   0.81193704]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.07106781   7.07106781]
 [ 16.          -7.86766174]
 [  8.           3.59897687]
 [ -8.         -12.59380921]
 [-16.          -2.50435991]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333  -3.08489716]
 [  5.66666667   6.45857386]
 [ -5.66666667   7.6117728 ]
 [-11.33333333  -3.07144047]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333   5.62697378]
 [  5.66666667  -9.38636107]
 [ -5.66666667  -8.45970343]
 [-11.33333333   0.4762459 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


27
The interpolation points are stored in the variable "EF_target_pos": 
[[ 22.89949494   9.89949494]
 [ 18.           3.07530778]
 [  9.           5.79670269]
 [ -9.          12.47221552]
 [-18.           7.2499977 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.36396103   6.36396103]
 [ 10.66666667  -4.37874768]
 [  5.33333333  -0.04693344]
 [ -5.33333333   4.5777698 ]
 [-10.66666667  -4.78971305]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.24264069  4.24264069]
 [ 8.66666667  4.43579916]
 [ 4.33333333 -1.73820338]
 [-4.33333333  2.08232312]
 [-8.66666667 -2.2522765 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667   2.13859149]
 [  6.33333333   8.01359038]
 [ -6.33333333  12.56757869]
 [-12.66666667   4.72733919]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.19238816   9.19238816]
 [ 13.33333333  -4.73565103]
 [  6.66666667  -0.64621891]
 [ -6.66666667   1.62606723]
 [-13.33333333   0.64296059]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.19238816   9.19238816]
 [ 15.33333333  -6.00742023]
 [  7.66666667  -9.82168244]
 [ -7.66666667   8.38384616]
 [-15.33333333   0.15824819]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.           0.52953308]
 [  6.          -1.52367175]
 [ -6.          -6.85383657]
 [-12.          -5.61419876]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   4.33835163]
 [  6.33333333  -7.74113343]
 [ -6.33333333  -0.27849617]
 [-12.66666667   3.6894476 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -3.75870154]
 [  5.33333333  -5.93721161]
 [ -5.33333333  -5.98037753]
 [-10.66666667   4.62856176]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.36396103  6.36396103]
 [ 9.33333333  4.22828659]
 [ 4.66666667  2.5653521 ]
 [-4.66666667 -0.77950462]
 [-9.33333333 -0.57256818]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   0.85355706]
 [  5.33333333   1.55904461]
 [ -5.33333333  -1.71476774]
 [-10.66666667  -1.59736642]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.77817459   7.77817459]
 [ 11.33333333   4.11300126]
 [  5.66666667   6.27648337]
 [ -5.66666667  -0.91117759]
 [-11.33333333   1.73926412]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.48528137   8.48528137]
 [ 12.          -0.58580648]
 [  6.          -0.08614978]
 [ -6.          -0.98056825]
 [-12.           2.59923771]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -3.56343629]
 [  5.33333333  -8.94127952]
 [ -5.33333333  -9.49368682]
 [-10.66666667   1.88950491]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333  -1.35656569]
 [  5.66666667  11.06436195]
 [ -5.66666667  -2.13083628]
 [-11.33333333  -5.1318488 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 22.19238816   9.19238816]
 [ 17.33333333   5.92115335]
 [  8.66666667 -12.66661634]
 [ -8.66666667  14.40665539]
 [-17.33333333  -3.32908641]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.48528137   8.48528137]
 [ 14.66666667  -1.68867298]
 [  7.33333333  -6.89942443]
 [ -7.33333333   7.45093211]
 [-14.66666667   0.76354127]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.65685425   5.65685425]
 [ 10.          -5.07803482]
 [  5.           6.89621081]
 [ -5.          -4.24281673]
 [-10.          -3.20823654]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.77817459   7.77817459]
 [ 15.33333333   4.24458491]
 [  7.66666667 -11.16246222]
 [ -7.66666667   1.94699359]
 [-15.33333333   4.93231097]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667   2.50103895]
 [  5.33333333  -4.38302413]
 [ -5.33333333   9.89237202]
 [-10.66666667  -4.96778242]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -0.01928654]
 [  5.33333333   9.88299549]
 [ -5.33333333   6.25232805]
 [-10.66666667  -4.92548611]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           2.77947567]
 [  7.          -8.59064449]
 [ -7.         -10.72542409]
 [-14.           1.76861372]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.65685425   5.65685425]
 [ 10.          -2.92644272]
 [  5.           9.74070657]
 [ -5.          -9.19688296]
 [-10.           4.16852729]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.36396103  6.36396103]
 [ 8.66666667 -3.10101788]
 [ 4.33333333 -2.91591301]
 [-4.33333333  7.57825377]
 [-8.66666667 -2.49180388]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


28
The interpolation points are stored in the variable "EF_target_pos": 
[[ 23.89949494   9.89949494]
 [ 18.66666667   4.17732942]
 [  9.33333333 -13.17745193]
 [ -9.33333333   0.49207748]
 [-18.66666667  -4.20154895]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333  -2.73189029]
 [  5.66666667  -1.38132211]
 [ -5.66666667   8.687218  ]
 [-11.33333333   5.40509382]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   3.86046271]
 [  5.66666667   6.42259088]
 [ -5.66666667   9.58407228]
 [-11.33333333  -3.35654564]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -2.56359349]
 [  7.          -5.12833952]
 [ -7.          -8.69822935]
 [-14.          -3.28769708]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.           5.89780024]
 [  6.          -8.61437176]
 [ -6.          -9.46813516]
 [-12.           1.29287201]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.           5.45960959]
 [  6.           7.40892619]
 [ -6.          11.65507857]
 [-12.           0.70355362]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.           2.95305326]
 [  7.           6.32227099]
 [ -7.          -2.979167  ]
 [-14.           4.16198377]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -2.11153415]
 [  5.66666667  -3.22866319]
 [ -5.66666667  -5.1527808 ]
 [-11.33333333  -4.90868639]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -5.71326308]
 [  7.         -13.90921174]
 [ -7.           9.80666024]
 [-14.          -2.57465768]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.36396103   6.36396103]
 [ 10.66666667   3.21095122]
 [  5.33333333   4.81568286]
 [ -5.33333333   3.96268086]
 [-10.66666667  -4.43285383]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.           1.7747117 ]
 [  6.           6.68987048]
 [ -6.           6.04968397]
 [-12.          -1.94003787]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.36396103   6.36396103]
 [ 10.66666667   4.49458414]
 [  5.33333333  -2.15688989]
 [ -5.33333333  -3.36642205]
 [-10.66666667   0.24791732]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.          -3.18440854]
 [  6.           0.74119452]
 [ -6.          -6.7195441 ]
 [-12.           2.22502768]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.          -6.89139231]
 [  7.          10.96065556]
 [ -7.           9.89223883]
 [-14.          -3.66285838]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.07106781   7.07106781]
 [ 12.          -1.68396818]
 [  6.          -9.52167036]
 [ -6.           3.40615633]
 [-12.          -4.56357222]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.48528137   8.48528137]
 [ 12.66666667   2.35762703]
 [  6.33333333  -6.74082816]
 [ -6.33333333  11.8004881 ]
 [-12.66666667   1.76888681]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.48528137   8.48528137]
 [ 12.66666667   5.89451724]
 [  6.33333333  -3.05225901]
 [ -6.33333333  -0.7968606 ]
 [-12.66666667  -6.37637896]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-898a7604bba6>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
