In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random

In [2]:

class FourLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.theta4 = np.deg2rad(90)
        self.l1 = np.random.randint(2,8)
        self.l2 = np.random.randint(2,8)
        self.l3 = np.random.randint(2,8)
        self.l4 = np.random.randint(2,8)

    def forwardKinematics(self, theta1, theta2, theta3,theta4):
        # Define the homogeneous transformation matrices for the 4-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.theta4 = theta4
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], 
                              [np.sin(self.theta1), np.cos(self.theta1), 0],
                              [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1],
                              [np.sin(self.theta2), np.cos(self.theta2), 0],
                              [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2],
                              [np.sin(self.theta3), np.cos(self.theta3), 0],
                              [0, 0, 1]])        
        self.t34 = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l3],
                              [np.sin(self.theta4), np.cos(self.theta4), 0],
                              [0, 0, 1]])
        self.t4end = np.matrix([[np.cos(self.theta4), -np.sin(self.theta4), self.l4],
                                [np.sin(self.theta4), np.cos(self.theta4), 0],
                                [0, 0, 1]])

        self.t0end = self.t01*self.t12*self.t23*self.t34*self.t4end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3 and joint 4
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        self.t04 = self.t01*self.t12*self.t23*self.t34
        # Find the x, y coordinates for joints 2 and 3 and 4. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        j4 = [ self.t04[0, 2], self.t04[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.jnt4pos, self.endEffPos = j2,j3,j4,endeff
        return j2,j3,j4,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, jnt4pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if jnt4pos is None:
            jnt4pos=self.jnt4pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        col3 = np.array(endEffPos + [0]) - np.array(jnt4pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2), np.cross(ai,col3)]).T 
        return J

In [3]:
def plotArm(jnt2pos, jnt3pos, jnt4pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, jnt4pos, endEffectPos,x2,y2, target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], jnt4pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], jnt4pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt3pos[0],x2[0]],[jnt3pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt3pos[0],x2[1]],[jnt3pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = FourLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45),np.deg2rad(45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3+arm.l4
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, joint4pos, endEffectorPos = init_joint2pos, init_joint3pos, init_joint4pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len=np.random.randint(2,arm.l3+1)
    
    keypoints_data=pd.DataFrame(columns=range((5+2)*2),dtype=float)

    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2],newTheta[3])
        joint2pos, joint3pos, joint4pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2]+np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
        
        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2]-np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],joint4pos[0],joint4pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, joint4pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motionv9/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((5+2,5+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[3][4]=1
    adj_mat[2][5]=1
    adj_mat[2][6]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motionv9/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motionv9/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
# create_simulation(8006,50)

In [6]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [7]:
for i in range(750,875):
    create_simulation(i,50)

16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -0.47200691]
 [  5.33333333   6.18348005]
 [ -5.33333333  -3.04054279]
 [-10.66666667  -1.67746398]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.36396103   6.36396103]
 [ 12.66666667  -3.07340682]
 [  6.33333333  11.45594195]
 [ -6.33333333  -3.66719922]
 [-12.66666667  -3.5357753 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   1.26236371]
 [  5.33333333   2.60770628]
 [ -5.33333333   7.22212465]
 [-10.66666667   1.66577797]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -4.99446556]
 [  6.         -10.62725964]
 [ -6.          -5.05099115]
 [-12.           4.27946394]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.36396103   6.36396103]
 [ 10.66666667  -1.35042081]
 [  5.33333333  -4.46472503]
 [ -5.33333333   1.33871965]
 [-10.66666667  -1.4949007 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   3.28884587]
 [  6.33333333 -10.20976134]
 [ -6.33333333   7.27231745]
 [-12.66666667  -2.38112724]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -1.47566165]
 [  6.33333333   3.04042165]
 [ -6.33333333   5.23471764]
 [-12.66666667   4.41913824]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.19238816   9.19238816]
 [ 14.66666667  -6.57417133]
 [  7.33333333   1.52158613]
 [ -7.33333333  -7.43595196]
 [-14.66666667   0.54521416]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -4.09043427]
 [  6.           2.65068396]
 [ -6.          -1.5559174 ]
 [-12.           2.62744132]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.19238816   9.19238816]
 [ 12.66666667   4.7732596 ]
 [  6.33333333   4.44539309]
 [ -6.33333333   2.97385312]
 [-12.66666667  -2.5746817 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.19238816   9.19238816]
 [ 15.33333333  -5.29888441]
 [  7.66666667 -10.429312  ]
 [ -7.66666667  -7.36397825]
 [-15.33333333   2.27242819]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.65685425   5.65685425]
 [ 10.66666667  -1.06766729]
 [  5.33333333   2.58850237]
 [ -5.33333333   7.2395472 ]
 [-10.66666667  -3.50888436]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           6.21861032]
 [  7.          -8.54845071]
 [ -7.          11.12778795]
 [-14.          -3.43707478]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           4.74170155]
 [  5.          -7.09417835]
 [ -5.           4.58100912]
 [-10.           2.63768059]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.36396103  6.36396103]
 [ 9.33333333 -1.50533208]
 [ 4.66666667  7.68546192]
 [-4.66666667  7.47209312]
 [-9.33333333 -0.99456756]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.19238816   9.19238816]
 [ 14.          -5.76315009]
 [  7.          -1.18497847]
 [ -7.          -3.87250747]
 [-14.          -0.81567078]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667   2.23263745]
 [  6.33333333 -10.79962515]
 [ -6.33333333  -0.04933638]
 [-12.66666667   5.76256273]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333  -5.64230725]
 [  5.66666667   2.01698651]
 [ -5.66666667  10.42119707]
 [-11.33333333   0.13556535]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.           2.60727276]
 [  6.          -9.70752449]
 [ -6.          -8.22933635]
 [-12.          -6.03580878]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.19238816   9.19238816]
 [ 14.          -1.96906541]
 [  7.         -11.95473319]
 [ -7.          10.09196054]
 [-14.           2.95462078]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   1.47166922]
 [  5.33333333  -5.53264588]
 [ -5.33333333   4.64994759]
 [-10.66666667  -2.45845236]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.07106781   7.07106781]
 [ 14.          -3.91247844]
 [  7.          -8.86045899]
 [ -7.          -7.83737895]
 [-14.          -3.24906255]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   5.6907589 ]
 [  6.66666667  -1.57995491]
 [ -6.66666667   8.43893909]
 [-13.33333333  -0.55471646]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -0.04862121]
 [  7.         -10.44109403]
 [ -7.         -13.89982699]
 [-14.           6.18671518]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -5.10472958]
 [  7.          -1.26793891]
 [ -7.           2.44917184]
 [-14.          -2.43923467]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -0.84689967]
 [  6.33333333  10.95351273]
 [ -6.33333333  -4.00215282]
 [-12.66666667  -0.7973118 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   2.587139  ]
 [  5.66666667  -8.40733637]
 [ -5.66666667   5.64810887]
 [-11.33333333  -1.64271601]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -4.1179532 ]
 [  7.33333333  -9.10307626]
 [ -7.33333333 -13.66996416]
 [-14.66666667   3.59795514]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.19238816   9.19238816]
 [ 14.           0.6866632 ]
 [  7.          12.80944884]
 [ -7.           8.47845684]
 [-14.           6.85221426]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.19238816   9.19238816]
 [ 14.66666667   5.76680338]
 [  7.33333333  11.30452348]
 [ -7.33333333 -10.05065331]
 [-14.66666667   7.35161221]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


27
The interpolation points are stored in the variable "EF_target_pos": 
[[ 23.19238816   9.19238816]
 [ 18.           0.49524363]
 [  9.         -12.11531263]
 [ -9.           6.36378636]
 [-18.           8.70667313]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.64852814e+01  8.48528137e+00]
 [ 1.33333333e+01 -1.16188372e-02]
 [ 6.66666667e+00  6.06667740e+00]
 [-6.66666667e+00 -7.23510556e+00]
 [-1.33333333e+01  6.16520900e+00]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.24264069  4.24264069]
 [ 7.33333333 -2.40362592]
 [ 3.66666667 -4.42681791]
 [-3.66666667  3.25121851]
 [-7.33333333 -3.47700946]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -0.31783578]
 [  5.          -4.36455094]
 [ -5.          -9.12621261]
 [-10.           2.42916099]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333 -0.1078002 ]
 [ 4.66666667  7.76510614]
 [-4.66666667 -2.25656377]
 [-9.33333333  0.92624338]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.89949494   9.89949494]
 [ 16.           4.10280127]
 [  8.          11.2780469 ]
 [ -8.         -11.02808645]
 [-16.          -1.88578312]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   4.94487626]
 [  6.66666667 -12.0536476 ]
 [ -6.66666667  10.75214975]
 [-13.33333333  -0.78297381]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   1.89323431]
 [  6.66666667  -2.473795  ]
 [ -6.66666667  -7.3404611 ]
 [-13.33333333   0.30928244]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.36396103   6.36396103]
 [ 13.33333333   1.66454522]
 [  6.66666667  -4.29801134]
 [ -6.66666667   8.02096542]
 [-13.33333333   2.99552978]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.19238816   9.19238816]
 [ 16.          -7.13135655]
 [  8.          12.6960888 ]
 [ -8.          -7.21214282]
 [-16.          -6.46497554]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667  -2.4571942 ]
 [  6.33333333  -5.65119653]
 [ -6.33333333  -4.00931743]
 [-12.66666667   0.33187871]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -3.8238831 ]
 [  5.33333333   4.15152544]
 [ -5.33333333  -0.13694114]
 [-10.66666667   3.14918856]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -1.31637141]
 [  6.          -8.24435899]
 [ -6.          -9.06543468]
 [-12.           5.49279783]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.           0.58780505]
 [  5.          -2.78001705]
 [ -5.          -5.73848412]
 [-10.          -5.04743271]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   1.62604587]
 [  5.66666667  -9.49495823]
 [ -5.66666667   1.27817906]
 [-11.33333333   5.13972585]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.48528137   8.48528137]
 [ 14.           4.33430873]
 [  7.           5.59320387]
 [ -7.           8.62187074]
 [-14.           3.29752244]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333  4.56971355]
 [ 4.66666667 -5.28363876]
 [-4.66666667 -1.85857938]
 [-9.33333333  2.32533315]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.89949494   9.89949494]
 [ 17.33333333  -1.42386229]
 [  8.66666667  -8.38998696]
 [ -8.66666667  10.3091914 ]
 [-17.33333333   7.90372819]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.          -0.39939681]
 [  7.           1.72060884]
 [ -7.         -12.44347146]
 [-14.          -3.22671068]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[10.36396103  6.36396103]
 [ 8.66666667  1.7557106 ]
 [ 4.33333333  7.74547085]
 [-4.33333333  7.91335958]
 [-8.66666667  1.7624497 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.           2.30365382]
 [  5.           8.14576331]
 [ -5.           6.53241218]
 [-10.          -1.79077853]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   6.72313184]
 [  6.66666667 -12.22255056]
 [ -6.66666667  -9.31787906]
 [-13.33333333   2.28719525]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333  3.42874743]
 [ 3.66666667  1.6887144 ]
 [-3.66666667  1.27307157]
 [-7.33333333  2.01824809]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.77817459   7.77817459]
 [ 15.33333333  -6.43170176]
 [  7.66666667 -12.71698725]
 [ -7.66666667   6.15612081]
 [-15.33333333   7.09366534]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -4.56962205]
 [  5.33333333  -9.76696544]
 [ -5.33333333  -5.20897359]
 [-10.66666667  -4.99330936]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.07106781   7.07106781]
 [ 15.33333333   7.09198317]
 [  7.66666667  -6.64093599]
 [ -7.66666667  13.51893454]
 [-15.33333333  -0.66263709]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.89949494   9.89949494]
 [ 16.          -4.56972145]
 [  8.         -13.45299705]
 [ -8.          14.85021801]
 [-16.           6.49141424]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -3.14772839]
 [  6.66666667  -6.00234792]
 [ -6.66666667  -5.62353321]
 [-13.33333333  -5.63032857]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.77817459   7.77817459]
 [ 10.66666667   0.15308467]
 [  5.33333333  -7.46943368]
 [ -5.33333333 -10.22098023]
 [-10.66666667   4.92205734]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -3.71302112]
 [  7.33333333   6.71438177]
 [ -7.33333333   0.19904552]
 [-14.66666667  -7.2494765 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           0.21561283]
 [  7.          11.67452774]
 [ -7.          12.41267052]
 [-14.          -4.24248388]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.07106781   7.07106781]
 [ 12.66666667  -6.48127175]
 [  6.33333333  -1.9730367 ]
 [ -6.33333333  -3.21725217]
 [-12.66666667   5.63457428]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.77817459   7.77817459]
 [ 16.           6.02968479]
 [  8.          11.87645902]
 [ -8.           0.83872013]
 [-16.          -7.15715262]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.53553391  3.53553391]
 [ 8.          0.64325117]
 [ 4.          4.00754049]
 [-4.         -4.58212712]
 [-8.          3.44494957]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.48528137   8.48528137]
 [ 10.66666667   2.8136696 ]
 [  5.33333333  -4.94285354]
 [ -5.33333333   1.13037167]
 [-10.66666667  -4.53157779]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.          -5.39630009]
 [  6.           2.24655874]
 [ -6.           2.22503489]
 [-12.          -0.36417955]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           2.02532147]
 [  7.          -2.6103372 ]
 [ -7.          -0.80070801]
 [-14.           2.94032173]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333  1.15203114]
 [ 4.66666667  2.52745151]
 [-4.66666667 -8.16341434]
 [-9.33333333 -3.02328896]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


11
The interpolation points are stored in the variable "EF_target_pos": 
[[ 9.82842712  2.82842712]
 [ 7.33333333 -2.44724041]
 [ 3.66666667 -5.44050663]
 [-3.66666667  6.14069167]
 [-7.33333333 -2.02750196]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333  -1.13440962]
 [  5.66666667 -10.73267687]
 [ -5.66666667  -3.4131509 ]
 [-11.33333333  -2.12575882]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.24810923]
 [  6.33333333  -9.36769162]
 [ -6.33333333   4.10594826]
 [-12.66666667   0.81593188]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.07106781   7.07106781]
 [ 14.66666667  -5.14417119]
 [  7.33333333   7.50052691]
 [ -7.33333333   7.06135248]
 [-14.66666667  -1.4781791 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.19238816   9.19238816]
 [ 14.66666667   2.38779564]
 [  7.33333333   2.10149007]
 [ -7.33333333   1.66921502]
 [-14.66666667  -1.14516702]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.          -0.5845538 ]
 [  5.           8.99785287]
 [ -5.          -1.34052271]
 [-10.          -3.69079365]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.65685425  5.65685425]
 [ 9.33333333  1.87499537]
 [ 4.66666667 -6.51941626]
 [-4.66666667  2.99166063]
 [-9.33333333 -2.09979409]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.77817459   7.77817459]
 [ 14.66666667   0.60687998]
 [  7.33333333   3.18484635]
 [ -7.33333333  14.32214157]
 [-14.66666667   5.1808916 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


26
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.89949494   9.89949494]
 [ 17.33333333   1.61769309]
 [  8.66666667 -12.24801361]
 [ -8.66666667  -5.47283325]
 [-17.33333333  -5.96283517]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -2.79693492]
 [  5.66666667  -4.06087202]
 [ -5.66666667   7.32229084]
 [-11.33333333  -3.15105831]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.48528137   8.48528137]
 [ 14.66666667   0.46996091]
 [  7.33333333   0.96412703]
 [ -7.33333333   7.44726425]
 [-14.66666667   4.99824152]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.77817459   7.77817459]
 [ 13.33333333  -0.07755128]
 [  6.66666667  -9.66073262]
 [ -6.66666667   7.66903842]
 [-13.33333333   3.31995974]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667  -4.13056574]
 [  5.33333333   3.76951257]
 [ -5.33333333  -5.73754515]
 [-10.66666667   0.87532345]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.94974747   4.94974747]
 [ 10.           1.404042  ]
 [  5.          -9.97226202]
 [ -5.           8.58522201]
 [-10.          -3.12264098]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.           3.57938   ]
 [  6.          -0.98520284]
 [ -6.          -7.16264936]
 [-12.          -4.91339154]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.07106781  7.07106781]
 [ 9.33333333 -1.87382074]
 [ 4.66666667 -2.56987871]
 [-4.66666667  5.22460352]
 [-9.33333333 -2.11636187]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   2.00742091]
 [  5.33333333 -10.37357749]
 [ -5.33333333   2.06345386]
 [-10.66666667   4.11279398]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.           5.37404763]
 [  6.          -6.05736509]
 [ -6.          -7.31926171]
 [-12.           4.48363848]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.94974747  4.94974747]
 [ 9.33333333  0.25059551]
 [ 4.66666667  6.14104375]
 [-4.66666667  8.28277172]
 [-9.33333333 -0.93823513]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333  -3.22924957]
 [  5.66666667   9.68980373]
 [ -5.66666667   2.26291668]
 [-11.33333333   0.27371502]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           6.83415166]
 [  7.          10.89945934]
 [ -7.           4.0633648 ]
 [-14.          -6.23282522]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   0.22380435]
 [  5.66666667   6.17315181]
 [ -5.66666667   0.88979793]
 [-11.33333333  -2.56970824]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


23
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.77817459   7.77817459]
 [ 15.33333333   1.52760757]
 [  7.66666667   2.25459563]
 [ -7.66666667 -15.18690772]
 [-15.33333333  -5.62043371]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.07106781   7.07106781]
 [ 13.33333333   5.01486785]
 [  6.66666667  11.72682766]
 [ -6.66666667  -4.84451366]
 [-13.33333333   2.0507361 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -1.2910615 ]
 [  5.33333333  10.48258444]
 [ -5.33333333   2.75737331]
 [-10.66666667  -5.30582866]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.48528137   8.48528137]
 [ 14.66666667  -3.07698047]
 [  7.33333333 -11.00875159]
 [ -7.33333333   3.15587113]
 [-14.66666667   6.45015644]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333   3.52160538]
 [  6.66666667  -6.42855651]
 [ -6.66666667 -11.46409542]
 [-13.33333333  -3.60958875]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.36396103   6.36396103]
 [ 12.66666667   2.2062968 ]
 [  6.33333333  -6.5613639 ]
 [ -6.33333333   0.65336878]
 [-12.66666667  -1.04972313]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   2.28545644]
 [  6.33333333 -10.03691151]
 [ -6.33333333  -1.79481161]
 [-12.66666667   0.43804266]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333   2.26251229]
 [  5.66666667  -0.87601501]
 [ -5.66666667   1.18660504]
 [-11.33333333   1.52356959]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   3.98651581]
 [  5.33333333   5.22908045]
 [ -5.33333333   9.71057687]
 [-10.66666667  -0.46431501]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.24264069  4.24264069]
 [ 8.          4.10469645]
 [ 4.         -1.17887353]
 [-4.          2.692288  ]
 [-8.         -2.5978036 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.          -0.64487726]
 [  7.           6.10055139]
 [ -7.           9.51049205]
 [-14.          -3.32931126]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.77817459   7.77817459]
 [ 12.66666667   0.55791428]
 [  6.33333333   3.95382208]
 [ -6.33333333  -2.31182014]
 [-12.66666667   4.63180554]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.48528137   8.48528137]
 [ 13.33333333   6.55746417]
 [  6.66666667   5.40503365]
 [ -6.66666667 -12.3630629 ]
 [-13.33333333  -5.16797304]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 12.65685425   5.65685425]
 [ 10.          -0.11430765]
 [  5.           8.46689395]
 [ -5.          -8.40045549]
 [-10.          -0.58998979]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -4.58194019]
 [  5.33333333   6.17357337]
 [ -5.33333333  -9.88137716]
 [-10.66666667  -1.59148256]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.07106781   7.07106781]
 [ 11.33333333   3.12124944]
 [  5.66666667  -1.87362648]
 [ -5.66666667 -10.41433217]
 [-11.33333333  -0.12603911]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           2.83986533]
 [  7.           8.05229175]
 [ -7.          -6.9815123 ]
 [-14.          -2.49494285]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[ 1.22426407e+01  4.24264069e+00]
 [ 9.33333333e+00 -1.82807089e+00]
 [ 4.66666667e+00 -5.38680839e-01]
 [-4.66666667e+00 -4.66856333e+00]
 [-9.33333333e+00 -4.35167929e-03]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           6.63657091]
 [  7.          -8.82912987]
 [ -7.          -6.85895959]
 [-14.           1.70924315]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.36396103   6.36396103]
 [ 12.           4.40742241]
 [  6.          -6.33339589]
 [ -6.           9.49231408]
 [-12.          -0.84298756]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.07106781   7.07106781]
 [ 10.66666667   1.77569796]
 [  5.33333333  -8.13098505]
 [ -5.33333333  -7.90358318]
 [-10.66666667  -3.92884563]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.36396103   6.36396103]
 [ 11.33333333   4.54104438]
 [  5.66666667   8.80492315]
 [ -5.66666667 -10.31368179]
 [-11.33333333   5.72887441]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.           7.0492259 ]
 [  7.           8.17977269]
 [ -7.          -4.70556338]
 [-14.           6.77916553]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   0.06364583]
 [  5.66666667  -0.68094746]
 [ -5.66666667   5.47471456]
 [-11.33333333   2.39738921]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -2.84389505]
 [  6.          -4.67387441]
 [ -6.          -7.41771867]
 [-12.          -5.59399344]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.07106781   7.07106781]
 [ 16.           6.96187891]
 [  8.           7.776266  ]
 [ -8.          -4.11972167]
 [-16.           0.05694831]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.77817459   7.77817459]
 [ 14.66666667   0.88162711]
 [  7.33333333 -11.11046871]
 [ -7.33333333  10.6420655 ]
 [-14.66666667   0.39920256]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.36396103   6.36396103]
 [ 14.66666667   2.02999561]
 [  7.33333333  -0.95157685]
 [ -7.33333333   2.9184054 ]
 [-14.66666667  -7.45515121]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.94974747   4.94974747]
 [ 12.          -2.19579105]
 [  6.           5.62265414]
 [ -6.          -0.4838175 ]
 [-12.          -3.39987585]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -0.1870766 ]
 [ 4.66666667  2.51785377]
 [-4.66666667  4.49864515]
 [-9.33333333  4.33341196]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.77817459   7.77817459]
 [ 12.          -5.75841458]
 [  6.           3.85740559]
 [ -6.          -6.07388549]
 [-12.          -0.51248942]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[11.65685425  5.65685425]
 [ 9.33333333  3.07452016]
 [ 4.66666667 -2.65662574]
 [-4.66666667 -6.14775392]
 [-9.33333333 -1.87826199]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -5.3243609 ]
 [  6.          -2.78752677]
 [ -6.           6.44430975]
 [-12.          -4.11187831]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.77817459   7.77817459]
 [ 14.           3.58574609]
 [  7.          -3.71511141]
 [ -7.           1.92363915]
 [-14.          -1.13304095]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.36396103   6.36396103]
 [ 14.          -6.706429  ]
 [  7.          -3.51935268]
 [ -7.          -5.14304291]
 [-14.          -3.62641536]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-9b304879dac9>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
