In [1]:
import numpy as np
import matplotlib.pyplot as plt
from celluloid import Camera
from IPython.display import HTML
import pandas as pd
import random
import copy

In [2]:

class ThreeLinkArm:
    
    def __init__(self):
        # Set parameters for the 3-link planar arm
        self.theta1 = np.deg2rad(0)
        self.theta2 = np.deg2rad(90)
        self.theta3 = np.deg2rad(90)
        self.orig_l1 = np.random.randint(4,9)
        self.orig_l2 = np.random.randint(4,9)
        self.orig_l3 = np.random.randint(4,9)
        self.l1=copy.copy(self.orig_l1)
        self.l2=copy.copy(self.orig_l2)
        self.l3=copy.copy(self.orig_l3)
        max_len_shift=int(np.min([self.l1,self.l2,self.l3])*(2/3))
        self.arr1=np.linspace(-max_len_shift,max_len_shift,np.random.randint(10,50))
        self.arr1=np.append(self.arr1,np.flip(self.arr1))
        self.permute=np.random.permutation([0.5,0.5,-1])


    def forwardKinematics(self, theta1, theta2, theta3):
        # Define the homogeneous transformation matrices for the 3-link planar arm
        self.theta1 = theta1
        self.theta2 = theta2
        self.theta3 = theta3
        self.t01 = np.matrix([[np.cos(self.theta1), -np.sin(self.theta1), 0], [np.sin(self.theta1), np.cos(self.theta1), 0], [0, 0, 1]])
        self.t12 = np.matrix([[np.cos(self.theta2), -np.sin(self.theta2), self.l1], [np.sin(self.theta2), np.cos(self.theta2), 0], [0, 0, 1]])
        self.t23 = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l2], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])        
        self.t3end = np.matrix([[np.cos(self.theta3), -np.sin(self.theta3), self.l3], [np.sin(self.theta3), np.cos(self.theta3), 0], [0, 0, 1]])
        self.t0end = self.t01*self.t12*self.t23*self.t3end
        return self.t0end
    
    def findJointPos(self): 
        # Find the x,y position of each joint and end effector so it can be plotted
        # Find the transformation matrices for joint 2 and joint 3
        self.t02 = self.t01*self.t12
        self.t03 = self.t01*self.t12*self.t23
        # Find the x, y coordinates for joints 2 and 3. Put them in a list j2 = [x,y]
        j2 = [ self.t02[0, 2], self.t02[1, 2] ]
        j3 = [ self.t03[0, 2], self.t03[1, 2] ]
        endeff = [self.t0end[0,2],self.t0end[1,2]]
        
        self.jnt2pos, self.jnt3pos, self.endEffPos = j2,j3,endeff
        return j2,j3,endeff
    
    def geomJacobian(self, jnt2pos=None, jnt3pos=None, endEffPos=None):
        if jnt2pos is None:
            jnt2pos=self.jnt2pos 
        if jnt3pos is None:
            jnt3pos=self.jnt3pos
        if endEffPos is None:
            endEffPos=self.endEffPos
        ai = np.array([0,0,1])
        col0 = np.array(endEffPos + [0])
        col1 = np.array(endEffPos + [0]) - np.array(jnt2pos + [0])
        col2 = np.array(endEffPos + [0]) - np.array(jnt3pos + [0])
        J = np.array([np.cross(ai,col0), np.cross(ai,col1), np.cross(ai,col2)]).T 
        return J
    
    def random_link_len_change(self,i):
        self.l1=self.orig_l1+self.permute[0]*self.arr1[i%len(self.arr1)]
        self.l2=self.orig_l2+self.permute[1]*self.arr1[i%len(self.arr1)]
        self.l3=self.orig_l3+self.permute[2]*self.arr1[i%len(self.arr1)]

In [3]:
def plotArm(jnt2pos, jnt3pos, endEffectPos, target=None, step=None):
    # set up figure
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(111, autoscale_on=False, xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    
    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')
        
    line, = ax.plot([], [], 'o-', lw=4, mew=5)
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.show()
    
# gif animation plotter
def plotArm2(jnt2pos, jnt3pos, endEffectPos,x2,y2,target=None, step=None, fig=None, camera=None):
    # set up figure
    ax = fig.add_subplot(111, autoscale_on=False,
                         xlim=(-25, 25), ylim=(-25, 25))
    ax.grid()
    line, = ax.plot([], [], 'o-', lw=4, mew=5, color='lightblue')
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

    line.set_data([], [])
    time_text.set_text('')
    x = np.array([0, jnt2pos[0], jnt3pos[0], endEffectPos[0]])
    y = np.array([0, jnt2pos[1], jnt3pos[1], endEffectPos[1]])
    line.set_data((x,y))
    
    plt.plot([jnt3pos[0],x2[0]],[jnt3pos[1],y2[0]],'o-', lw=2, mew=5, color='black')
    plt.plot([jnt3pos[0],x2[1]],[jnt3pos[1],y2[1]],'o-', lw=2, mew=5, color='black')


    if step is not None:
        step = np.array(step)
        plt.scatter(step[:, 0],step[:, 1], color='lightblue', marker='o')
        plt.plot(step[:, 0],step[:, 1], color='lightblue')
    if target is not None:
        target = np.array(target)
        plt.scatter(target[:, 0],target[:, 1], color='red', marker='o')

    camera.snap()

In this part, let's plan some simple polynomial trajectories in the work space. 

First, setup a simple environment with the arm manipulator and four intermediate interpolation points.

In [4]:
def create_simulation(animation_index,samples):
    
    # Setup our new manipulator
    arm = ThreeLinkArm()
    
    # define the initial configuration of the manipulator (you are welcomed to try other values)
    initTheta = [np.deg2rad(0),np.deg2rad(45),np.deg2rad(-45)]

    # Initialise the arm with the initial values
    _ = arm.forwardKinematics(*initTheta)

    # Get the initial end-effector position 
    init_joint2pos, init_joint3pos, EF_init_pos = arm.findJointPos()

    # Define the target postions of the end-effector
    # EF_target_pos = np.array([[EF_init_pos[0], 6.,2.,-4.,-8.],
    #                           [EF_init_pos[1], -6.,8.,-5.,6.]]).T
    ##Choose points randomly, choose x equally spaced and y randomly
    L=arm.l1+arm.l2+arm.l3
    print(L)
    x_points=np.array([2/3*L, 1/3*L, -1/3*L, -2/3*L])

    y_points=[]
    R=3*L/4
    for i in range(4):
        y_points.append(random.uniform(-1*np.sqrt(R**2-x_points[i]**2),
                                          np.sqrt(R**2-x_points[i]**2)))
    y_points=np.array(y_points)
    
    EF_target_pos = np.array([[EF_init_pos[0], x_points[0],x_points[1],x_points[2],x_points[3]],
                              [EF_init_pos[1], y_points[0],y_points[1],y_points[2],y_points[3]]]).T

    # Plot the pose of the arm
    #plotArm(*arm.findJointPos(), target=EF_target_pos)
    print(f"The interpolation points are stored in the variable \"EF_target_pos\": \n{EF_target_pos}")
    
    pol = np.polyfit(EF_target_pos[:, 0], EF_target_pos[:, 1], EF_target_pos.shape[0]-1)  # polynomial coefficients
    
    # Plotting the planned trajectory
    #epsilon = 100
    epsilon = samples
    
    xx = np.linspace(EF_target_pos[0,0],EF_target_pos[-1,0], epsilon)
    yy = np.polyval(pol,xx)   
    curve = np.hstack([xx[:, None], yy[:, None]]) 
    
    interpolated_points=curve

#     plotArm(*arm.findJointPos(), target=EF_target_pos, step=interpolated_points)
    print(f"The intermediate points are stored in the variable \"interpolated_points\"")
    
    # set the current E-F position for the IK loop
    joint2pos, joint3pos, endEffectorPos = init_joint2pos, init_joint3pos, EF_init_pos
    # set the initial robot configuration
    newTheta = initTheta

    # Set up the animation generator
    fig = plt.figure(figsize=(10,10))
    camera = Camera(fig)
    
    temp_eeff_angle=np.append(np.linspace(0,45,int(interpolated_points.shape[0]/8)),
                          np.linspace(45,0,int(interpolated_points.shape[0]/8)))
    
    wrist_len_orig=np.random.randint(2,arm.l3+1)
    
    keypoints_data=pd.DataFrame(columns=range((4+2)*2),dtype=float)
    
    arr2=np.linspace(-int(wrist_len_orig/2),int(wrist_len_orig/2),np.random.randint(10,50))
    
    arr2=np.append(arr2,np.flip(arr2))


    for i in range(interpolated_points.shape[0]):
        J = arm.geomJacobian()

        newgoal = interpolated_points[i, :]
        deltaStep = newgoal - endEffectorPos
        subtarget = np.array([deltaStep[0], deltaStep[1], 0]) 

        radTheta = np.linalg.pinv(J) @ subtarget
        newTheta = newTheta + radTheta

        # ----------- Do forward kinematics to plot the arm ---------------
        arm.random_link_len_change(i)
        wrist_len=wrist_len_orig+arr2[i%len(arr2)]

        _ = arm.forwardKinematics(newTheta[0],newTheta[1],newTheta[2])
        joint2pos, joint3pos, endEffectorPos = arm.findJointPos()

        x2=[]
        y2=[]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2] \
                                 +np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2] \
                                 +np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        x2=x2+[arm.l1*np.cos(newTheta[0]) \
               +arm.l2*np.cos(newTheta[0]+newTheta[1]) \
               +wrist_len*np.cos(newTheta[0]+newTheta[1]+newTheta[2] \
                                 -np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]
    
        y2=y2+[arm.l1*np.sin(newTheta[0]) \
               +arm.l2*np.sin(newTheta[0]+newTheta[1]) \
               +wrist_len*np.sin(newTheta[0]+newTheta[1]+newTheta[2] \
                                 -np.deg2rad(temp_eeff_angle[i%len(temp_eeff_angle)]))]

        temp_keypoints=np.array([0,0,joint2pos[0],joint2pos[1],joint3pos[0],joint3pos[1],
                                 endEffectorPos[0],endEffectorPos[1]])
        
        temp_keypoints=np.append(temp_keypoints,np.array([x2[0],y2[0],x2[1],y2[1]]))
        
        keypoints_data = keypoints_data.append(pd.DataFrame(temp_keypoints[None,:],columns=keypoints_data.columns),
                                               ignore_index = True)
        
        plotArm2(joint2pos, joint3pos, endEffectorPos,x2,y2, target=EF_target_pos, fig=fig, camera=camera)


    plt.close()
    animation = camera.animate()
    animation.save('./animated_motion_dynamic_len/animated_motion'+str(animation_index)+'.gif', writer = 'imagemagick')
    
    # create the adjacency matrix
    adj_mat=np.zeros((4+2,4+2))
    adj_mat[0][1]=1
    adj_mat[1][2]=1
    adj_mat[2][3]=1
    adj_mat[2][4]=1
    adj_mat[2][5]=1
    
    pd.DataFrame(adj_mat).astype(int).to_csv('./animated_motion_dynamic_len/adj_mat'+str(animation_index)+'.csv')
    keypoints_data.to_csv('./animated_motion_dynamic_len/ts_data'+str(animation_index)+'.csv')    
    

In [5]:
import os
os.environ['MAGICK_THREAD_LIMIT'] = '2'

In [6]:
# create_simulation(1023,50)

In [7]:
for i in range(375,500):
    create_simulation(i,50)

18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           0.72892543]
 [  6.           3.10412445]
 [ -6.          -8.22592035]
 [-12.          -4.99430687]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           7.15357432]
 [  7.           5.35068253]
 [ -7.          -9.868771  ]
 [-14.           4.86694086]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   4.13062358]
 [  5.66666667  -1.86475057]
 [ -5.66666667  -0.17797631]
 [-11.33333333   3.03758868]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.          -6.20439847]
 [  7.          -4.56550237]
 [ -7.          -9.93791599]
 [-14.           1.61039978]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           2.03471675]
 [  7.          -3.91439816]
 [ -7.          -8.75748431]
 [-14.           4.98195153]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   2.67055714]
 [  5.66666667 -10.0319739 ]
 [ -5.66666667  -9.44674099]
 [-11.33333333   4.26079009]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.          -5.69621431]
 [  6.          -6.41031236]
 [ -6.           4.45225302]
 [-12.          -2.93580147]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667   0.06560485]
 [  6.33333333  -9.3649049 ]
 [ -6.33333333   1.59900458]
 [-12.66666667  -3.28110026]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          2.5046819 ]
 [ 4.          6.89862037]
 [-4.         -6.74353321]
 [-8.         -4.059807  ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   3.42321574]
 [  5.33333333   3.87077591]
 [ -5.33333333  -0.22626918]
 [-10.66666667   4.87082945]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.65685425   5.65685425]
 [ 16.           5.67999991]
 [  8.          -1.45646108]
 [ -8.          14.80454665]
 [-16.           2.35814222]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333  -1.8119562 ]
 [  6.66666667  -9.75764214]
 [ -6.66666667  -0.86311636]
 [-13.33333333   0.96123523]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -3.7488756 ]
 [  6.33333333  -1.57672338]
 [ -6.33333333  -1.33885469]
 [-12.66666667   4.03214157]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667   5.08495109]
 [  6.33333333  -9.80789135]
 [ -6.33333333 -11.02127583]
 [-12.66666667  -0.42200588]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   4.57082352]
 [  5.66666667  -5.96642593]
 [ -5.66666667   9.80397292]
 [-11.33333333   4.01249383]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   5.4888137 ]
 [  5.66666667  -1.0438037 ]
 [ -5.66666667  10.67118999]
 [-11.33333333   1.77785386]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           2.66504968]
 [  7.          11.21356941]
 [ -7.          -2.30778527]
 [-14.          -4.79471082]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -4.69917491]
 [  5.33333333  -5.55225339]
 [ -5.33333333   2.52748594]
 [-10.66666667   0.46121827]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           0.30086801]
 [  5.           9.42052987]
 [ -5.           3.69624421]
 [-10.          -3.95470183]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   0.96200071]
 [  5.66666667  -3.2922766 ]
 [ -5.66666667   1.41215484]
 [-11.33333333  -4.9088291 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   1.44405474]
 [  5.66666667  -4.54697026]
 [ -5.66666667  -0.75114213]
 [-11.33333333  -5.24890045]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           1.21468805]
 [  6.           8.53307224]
 [ -6.           6.65653728]
 [-12.           3.96853761]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -4.582795  ]
 [  6.66666667 -12.95252776]
 [ -6.66666667   9.41187018]
 [-13.33333333   0.67295119]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -1.86394365]
 [  6.          -3.75394644]
 [ -6.         -11.61026519]
 [-12.          -6.17973913]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.53553391   3.53553391]
 [ 13.33333333   5.68703977]
 [  6.66666667   4.41257599]
 [ -6.66666667   3.52581239]
 [-13.33333333  -5.0009451 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -3.35714847]
 [  5.33333333  -2.51750621]
 [ -5.33333333  -1.98701046]
 [-10.66666667   1.36307919]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           0.12854443]
 [  6.          -7.59113106]
 [ -6.          -7.68058975]
 [-12.           1.34420839]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           4.1639948 ]
 [  5.           6.61449155]
 [ -5.           7.73333675]
 [-10.          -3.13013445]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.           2.63321306]
 [  7.           3.18802115]
 [ -7.           5.26895967]
 [-14.          -0.75929519]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -1.09855263]
 [  5.33333333   4.20586122]
 [ -5.33333333   0.69699157]
 [-10.66666667  -0.62250229]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.82842712   2.82842712]
 [ 12.66666667   3.91463193]
 [  6.33333333 -10.26515317]
 [ -6.33333333   6.03051983]
 [-12.66666667  -5.32609763]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  0.54593961]
 [ 4.66666667  2.26184666]
 [-4.66666667  8.97988001]
 [-9.33333333 -2.40746755]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.53553391   3.53553391]
 [ 14.          -0.86863585]
 [  7.           3.79640457]
 [ -7.          12.09153614]
 [-14.          -4.33412822]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -4.16959198]
 [  6.33333333  -4.48675611]
 [ -6.33333333  -6.99796341]
 [-12.66666667   2.65949536]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.82842712   2.82842712]
 [ 13.33333333  -3.88630831]
 [  6.66666667 -10.80798818]
 [ -6.66666667   6.18838913]
 [-13.33333333   3.77323463]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -2.29712693]
 [  5.66666667  -5.82316828]
 [ -5.66666667   2.78474725]
 [-11.33333333   3.00428532]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667  -2.02725223]
 [  5.33333333   0.505426  ]
 [ -5.33333333   4.25307482]
 [-10.66666667  -4.27318827]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -3.14535456]
 [  6.66666667  -7.07883171]
 [ -6.66666667  13.09395921]
 [-13.33333333  -3.04607045]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667  -0.35729921]
 [  5.33333333  -2.59032909]
 [ -5.33333333   8.99578246]
 [-10.66666667  -2.00337882]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.94974747   4.94974747]
 [ 14.          -3.56155157]
 [  7.           0.6925446 ]
 [ -7.           8.4157167 ]
 [-14.          -4.05642089]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333  -3.29248313]
 [  6.66666667  -4.14060236]
 [ -6.66666667  -9.62058705]
 [-13.33333333  -6.09396715]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.53553391   3.53553391]
 [ 13.33333333   1.22919908]
 [  6.66666667  -6.8636302 ]
 [ -6.66666667  11.753644  ]
 [-13.33333333   2.91257386]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.53553391   3.53553391]
 [ 10.66666667   0.6521818 ]
 [  5.33333333   4.83740785]
 [ -5.33333333  -0.48439283]
 [-10.66666667   2.63730633]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667   3.16369447]
 [  6.33333333  -8.98123763]
 [ -6.33333333   7.36205003]
 [-12.66666667  -1.27568756]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.82842712   2.82842712]
 [ 12.66666667   3.94969883]
 [  6.33333333   1.27486579]
 [ -6.33333333   9.16023008]
 [-12.66666667  -1.74729738]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667   0.43549051]
 [  5.33333333   7.53036642]
 [ -5.33333333  -9.62084792]
 [-10.66666667   0.46082586]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -3.73943955]
 [  5.66666667   4.89219309]
 [ -5.66666667  -2.60485481]
 [-11.33333333  -1.64229831]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.82842712   2.82842712]
 [ 10.66666667  -3.97636044]
 [  5.33333333   9.74698788]
 [ -5.33333333   1.04683759]
 [-10.66666667   1.22159865]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           2.7986643 ]
 [  6.         -11.88859183]
 [ -6.           4.47022026]
 [-12.           4.64609199]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667  -2.37629325]
 [  6.33333333 -11.80193302]
 [ -6.33333333  12.33124003]
 [-12.66666667  -4.96609942]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           0.06366157]
 [  7.           8.48518387]
 [ -7.          -8.52704771]
 [-14.          -7.11195725]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.24264069   4.24264069]
 [ 10.           2.28856508]
 [  5.           0.86193124]
 [ -5.           9.53717178]
 [-10.           0.82303011]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.82842712   2.82842712]
 [ 13.33333333   4.52665571]
 [  6.66666667  10.87146789]
 [ -6.66666667  -9.43644632]
 [-13.33333333  -4.75304555]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333  -6.60875824]
 [  6.66666667   0.54513793]
 [ -6.66666667  -1.87440562]
 [-13.33333333   5.95419824]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           4.97442786]
 [  7.          -7.11330274]
 [ -7.          10.33456023]
 [-14.           3.39590635]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  0.33294553]
 [ 4.66666667 -4.30199847]
 [-4.66666667  7.08261381]
 [-9.33333333 -3.24586384]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   4.02132169]
 [  5.33333333   5.65366567]
 [ -5.33333333   4.89525665]
 [-10.66666667   5.36151237]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           4.21856626]
 [  6.          -6.41372583]
 [ -6.           8.40508093]
 [-12.           1.96650576]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333   1.2495656 ]
 [  6.66666667   6.99032054]
 [ -6.66666667   5.55904748]
 [-13.33333333  -1.33614763]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           1.52739034]
 [  6.          10.15957894]
 [ -6.           7.86265377]
 [-12.           5.98167652]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           1.25215479]
 [  6.          -1.72973432]
 [ -6.          -1.1378735 ]
 [-12.           4.59920603]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -2.39912325]
 [  6.           5.22572382]
 [ -6.         -10.87324595]
 [-12.          -2.7972668 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           1.36903687]
 [  7.          -9.00496277]
 [ -7.          13.40223658]
 [-14.           1.97287991]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.53553391   3.53553391]
 [ 12.66666667   4.62332536]
 [  6.33333333  -8.26756493]
 [ -6.33333333  10.89533321]
 [-12.66666667   5.38456839]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           0.98165076]
 [  5.           6.89249112]
 [ -5.          -1.5833312 ]
 [-10.          -2.35907471]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  4.52735687]
 [ 4.66666667 -7.65760297]
 [-4.66666667 -2.74190702]
 [-9.33333333 -4.42197501]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   2.35354403]
 [  6.33333333  -2.250895  ]
 [ -6.33333333  -8.11701902]
 [-12.66666667   3.31470162]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.53553391   3.53553391]
 [ 13.33333333   5.8654337 ]
 [  6.66666667   0.0877536 ]
 [ -6.66666667   2.73747474]
 [-13.33333333  -2.45039539]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -3.99796602]
 [  6.33333333  -4.3146353 ]
 [ -6.33333333  -4.02923719]
 [-12.66666667  -4.10597719]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333   2.15604809]
 [  6.66666667  -5.99817283]
 [ -6.66666667   2.37092978]
 [-13.33333333   2.4794558 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -5.70352775]
 [  6.           3.97139233]
 [ -6.          -0.82812578]
 [-12.           4.00209958]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           1.96347055]
 [  6.          -6.36378301]
 [ -6.          -5.91854553]
 [-12.          -6.17054916]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333   4.8826676 ]
 [  5.66666667   6.48432125]
 [ -5.66666667   7.30413368]
 [-11.33333333  -2.38353998]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   3.89839855]
 [  6.33333333   7.89201036]
 [ -6.33333333  -4.57515829]
 [-12.66666667  -3.11038514]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.82842712  2.82842712]
 [ 9.33333333  4.0880133 ]
 [ 4.66666667 -5.43067668]
 [-4.66666667 -6.14894567]
 [-9.33333333  3.9405146 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


13
The interpolation points are stored in the variable "EF_target_pos": 
[[11.53553391  3.53553391]
 [ 8.66666667 -3.94377455]
 [ 4.33333333 -0.92912161]
 [-4.33333333 -7.48189435]
 [-8.66666667  0.64325444]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333  -4.25117698]
 [  5.66666667   1.15986529]
 [ -5.66666667  -8.37071914]
 [-11.33333333   1.61195491]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.24264069   4.24264069]
 [ 10.66666667   2.60023158]
 [  5.33333333   3.13650662]
 [ -5.33333333   7.42793879]
 [-10.66666667  -3.98605668]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           3.35525826]
 [  6.          11.87666982]
 [ -6.          -0.11445629]
 [-12.           4.00387598]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.65685425   5.65685425]
 [ 10.66666667  -1.51409923]
 [  5.33333333  -0.38554866]
 [ -5.33333333   0.05035172]
 [-10.66666667   4.41605631]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667  -0.44103978]
 [  6.33333333  -7.92078564]
 [ -6.33333333  -4.24633358]
 [-12.66666667  -2.9046699 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   5.76752102]
 [  6.33333333  12.51435386]
 [ -6.33333333  -3.6181656 ]
 [-12.66666667   0.22952379]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           2.48873435]
 [  5.          -6.23872195]
 [ -5.           6.87637105]
 [-10.           0.97895514]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333   3.07183849]
 [  5.66666667   2.75175619]
 [ -5.66666667   9.96323589]
 [-11.33333333  -4.26574912]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           3.9055212 ]
 [  6.           1.80417366]
 [ -6.          -9.3476526 ]
 [-12.           2.61033579]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333   3.31599599]
 [  6.66666667   7.40092305]
 [ -6.66666667 -11.08499615]
 [-13.33333333  -0.35700987]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.          -4.62777077]
 [  5.           5.20223538]
 [ -5.          -7.59760409]
 [-10.           1.57400694]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


24
The interpolation points are stored in the variable "EF_target_pos": 
[[ 21.65685425   5.65685425]
 [ 16.           0.05195285]
 [  8.         -13.8975692 ]
 [ -8.          -3.49362553]
 [-16.          -3.55423618]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 20.24264069   4.24264069]
 [ 14.66666667  -6.72036012]
 [  7.33333333  -8.92703908]
 [ -7.33333333 -10.89632467]
 [-14.66666667   2.54736313]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.94974747   4.94974747]
 [ 13.33333333  -5.86288864]
 [  6.66666667  -0.42387838]
 [ -6.66666667  -7.68530726]
 [-13.33333333  -4.46536881]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.82842712   2.82842712]
 [ 10.           0.3505611 ]
 [  5.          -5.92694093]
 [ -5.           1.61406201]
 [-10.          -4.32522497]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           3.96879098]
 [  6.           9.00425682]
 [ -6.         -11.19027221]
 [-12.           2.1800175 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           0.68673689]
 [  6.          -0.65837431]
 [ -6.         -11.84275222]
 [-12.           4.18077282]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           3.3964078 ]
 [  6.          10.43540314]
 [ -6.           1.92182646]
 [-12.           0.88237509]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


21
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.65685425   5.65685425]
 [ 14.           2.40843793]
 [  7.          -6.89533078]
 [ -7.         -13.16620237]
 [-14.          -0.63819999]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 18.24264069   4.24264069]
 [ 13.33333333  -0.7541474 ]
 [  6.66666667   2.92163   ]
 [ -6.66666667  -4.86013279]
 [-13.33333333  -2.26140442]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.          -3.20769394]
 [  5.          -6.36713791]
 [ -5.           8.87939941]
 [-10.          -5.00429128]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   0.50271625]
 [  6.33333333  -5.32601146]
 [ -6.33333333   8.08084083]
 [-12.66666667  -0.1815361 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


22
The interpolation points are stored in the variable "EF_target_pos": 
[[ 19.65685425   5.65685425]
 [ 14.66666667  -0.40286027]
 [  7.33333333 -11.24578328]
 [ -7.33333333   9.66935155]
 [-14.66666667  -4.82480699]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.82842712   2.82842712]
 [ 12.           1.47462851]
 [  6.         -10.47149028]
 [ -6.           3.93276268]
 [-12.          -0.83989507]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -3.07837046]
 [  5.66666667   0.76611537]
 [ -5.66666667  -5.14406325]
 [-11.33333333  -3.36488169]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.53553391  3.53553391]
 [ 9.33333333  3.33979828]
 [ 4.66666667  6.34627394]
 [-4.66666667 -2.56910092]
 [-9.33333333 -4.58744728]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -5.82674045]
 [  6.33333333   0.19186667]
 [ -6.33333333 -11.28407023]
 [-12.66666667  -0.66176933]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


15
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.53553391   3.53553391]
 [ 10.          -2.04647715]
 [  5.          -6.22579877]
 [ -5.          -2.53423274]
 [-10.          -0.57929186]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.          -0.94709145]
 [  6.          -0.66151338]
 [ -6.           6.05743442]
 [-12.          -3.77803534]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


12
The interpolation points are stored in the variable "EF_target_pos": 
[[10.82842712  2.82842712]
 [ 8.          3.42667786]
 [ 4.         -5.7034418 ]
 [-4.          0.46228879]
 [-8.          0.81726844]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667   3.79835817]
 [  6.33333333  -0.59876185]
 [ -6.33333333   3.07493852]
 [-12.66666667   0.60984823]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -3.89543031]
 [  6.33333333   2.52991724]
 [ -6.33333333  -6.17265081]
 [-12.66666667   2.42800699]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.65685425   5.65685425]
 [ 12.66666667  -0.89994881]
 [  6.33333333 -12.50332933]
 [ -6.33333333   2.37634819]
 [-12.66666667  -0.51769645]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.94974747   4.94974747]
 [ 12.66666667  -2.28533627]
 [  6.33333333   9.08377441]
 [ -6.33333333   6.19829953]
 [-12.66666667   4.12435371]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


19
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.24264069   4.24264069]
 [ 12.66666667   3.54633698]
 [  6.33333333  -8.38447784]
 [ -6.33333333 -10.27956426]
 [-12.66666667  -0.81571365]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.65685425   5.65685425]
 [ 11.33333333  -1.14426487]
 [  5.66666667 -10.25535223]
 [ -5.66666667  -2.12704195]
 [-11.33333333   3.05989111]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -4.21045956]
 [  5.66666667  -2.3863803 ]
 [ -5.66666667  -3.48186535]
 [-11.33333333  -3.00286132]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.           0.56039118]
 [  6.          -3.69322521]
 [ -6.          -3.45425534]
 [-12.          -3.89922535]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.65685425   5.65685425]
 [ 12.           2.98354471]
 [  6.           1.31484464]
 [ -6.           3.40737249]
 [-12.          -1.35940662]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333  -5.19300343]
 [  5.66666667   3.19457673]
 [ -5.66666667  -8.57213277]
 [-11.33333333  -3.2545484 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 14.94974747   4.94974747]
 [ 11.33333333   5.27725862]
 [  5.66666667   1.17436748]
 [ -5.66666667  -8.62328757]
 [-11.33333333   3.14032985]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


14
The interpolation points are stored in the variable "EF_target_pos": 
[[12.24264069  4.24264069]
 [ 9.33333333 -2.17286335]
 [ 4.66666667 -6.74326655]
 [-4.66666667  5.1899595 ]
 [-9.33333333 -2.59047034]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.24264069   4.24264069]
 [ 11.33333333   3.33619178]
 [  5.66666667  -4.38872387]
 [ -5.66666667   5.92908233]
 [-11.33333333  -5.16214044]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


16
The interpolation points are stored in the variable "EF_target_pos": 
[[ 13.94974747   4.94974747]
 [ 10.66666667   5.20109332]
 [  5.33333333   3.11022204]
 [ -5.33333333   6.70834557]
 [-10.66666667  -0.65103493]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


17
The interpolation points are stored in the variable "EF_target_pos": 
[[ 15.53553391   3.53553391]
 [ 11.33333333  -0.08103957]
 [  5.66666667   0.01757535]
 [ -5.66666667   5.87185796]
 [-11.33333333   4.76548566]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.           5.84341114]
 [  6.           8.38217161]
 [ -6.          -3.12340788]
 [-12.           3.2211029 ]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.24264069   4.24264069]
 [ 12.          -5.64931544]
 [  6.          -4.6333218 ]
 [ -6.           2.30385949]
 [-12.           2.46181177]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


20
The interpolation points are stored in the variable "EF_target_pos": 
[[ 17.65685425   5.65685425]
 [ 13.33333333  -3.46433985]
 [  6.66666667 -11.32660264]
 [ -6.66666667   5.1940273 ]
 [-13.33333333  -3.88916975]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,


18
The interpolation points are stored in the variable "EF_target_pos": 
[[ 16.53553391   3.53553391]
 [ 12.          -5.72629969]
 [  6.           0.51856308]
 [ -6.           6.34890316]
 [-12.           5.71537958]]
The intermediate points are stored in the variable "interpolated_points"


<ipython-input-3-e5129fb5eb54>:29: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax = fig.add_subplot(111, autoscale_on=False,
